failed_transactions.message=You have {0} transaction(s) with the {1} status(es).
failed_transactions.description=Checks the Transactions Module to see if there are any transactions with failed statuses.

migrate_billing_agreement.message=You have {0} Billing Agreement(s) not converted. Please see the job output file located at: {1} for more details.
migrate_billing_agreement.description=Some of the Billing Agreement(s) not converted, for more details see the output file. Try to run job once again in order to convert all the BA IDs to Vault tokens.
