button.save=Save

locations.all=all {0} locations

color.black=black
color.white=white
color.white.outline=white-outline

location.label=Choose a location:
location.pdp=pdp
location.pvp=pvp
location.cart=cart
location.login=login
location.billing=billing
location.minicart=minicart

checkbox.apply.all=Apply to all {0} locations

smartbutton.saved.title=PayPal and Venmo Buttons configuration successfully saved for {0}

smartbutton.height.title=Choose a height:
smartbutton.max.height=min: 25
smartbutton.min.height=max: 55

smartbutton.color.title=Choose a color:
smartbutton.color.option.gold=gold
smartbutton.color.option.blue=blue
smartbutton.color.option.black=black
smartbutton.color.option.white=white
smartbutton.color.option.silver=silver

smartbutton.shape.title=Choose a shape:
smartbutton.shape.option.rect=rect
smartbutton.shape.option.pill=pill

smartbutton.label.title=Choose a label:
smartbutton.label.option.checkout=checkout
smartbutton.label.option.paypal=paypal
smartbutton.label.option.buynow=buynow
smartbutton.label.option.pay=pay
smartbutton.label.option.installment=installment
smartbutton.label.option.donate=donate
smartbutton.label.option.subscribe=subscribe
smartbutton.label.tooltip=The installment feature is available only in MX and BR.

paypal.location.title=PayPal and Venmo Buttons Style Configurations
paypal.location.billing=billing
paypal.location.cart=cart
paypal.location.minicart=minicart
paypal.location.pdp=pdp
paypal.location.pvp=pvp

venmo.eligibility.note=Note: Venmo is not eligible, as it is currently supported only in the US location.

paylater.messaging.saved.title=Changes were successfully published
paylater.messaging.not.saved.title=Changes weren't published
paylater.messaging.not.active=Please activate PayPal Pay Later messaging on the PayPal Plugin > Preference Configuration > Pay Later Banners/Messaging tab using "PayPal Pay Later Messaging Location" site preference.

button.message.title=PayPal Button Messaging Configuration
button.message.not.eligible.message=Note: Messaging is currently only supported for US merchants and US customers. Merchants must be eligible for Pay Later to display Pay Later offers with buttons.
button.message.option.cart=cart
button.message.option.minicart=minicart
button.message.option.pdp=pdp
button.message.option.pvp=pvp
button.message.option.billing=billing

button.message.align=Choose an align:
button.message.align.option.center=center
button.message.align.option.left=left
button.message.align.option.right=right

button.message.color=Choose a color:
button.message.color.option.black=black
button.message.color.option.white=white

button.message.position=Choose a position:
button.message.position.option.top=top
button.message.position.option.bottom=bottom

button.message.saved.title=PayPal Button message configuration successfully saved for {0}

tab.paypal.venmo=PayPal and Venmo
tab.cwpp=Connect with PayPal
tab.cardfields=Card Fields
tab.apple-pay=Apple Pay
tab.google-pay=Google Pay
tab.paylater.configurations=PayPal Pay Later Configurations

payment.method.disabled.label=Please enable this payment method(s) in
bm.payment.methods=Business Manager — Payment Methods

applepay.title=Apple Pay Button Configuration
applepay.saved.title=Apple Pay Button configuration successfully saved for {0}
applepay.color.label=Choose a color:
applepay.location.label=Choose a location:
applepay.type.label=Choose a type:

googlepay.title=Google Pay Button Configuration
googlepay.location.label=Choose a location:
googlepay.color.label=Choose a color:
googlepay.color.option.default=default
googlepay.color.option.black=black
googlepay.color.option.white=white
googlepay.type.label=Choose a type:
googlepay.type.option.book=book
googlepay.type.option.buy=buy
googlepay.type.option.checkout=checkout
googlepay.type.option.donate=donate
googlepay.type.option.order=order
googlepay.type.option.pay=pay
googlepay.type.option.plain=plain
googlepay.type.option.subscribe=subscribe
googlepay.corner.radius.label=Choose a corner radius:
googlepay.corner.radius.min=min: 0
googlepay.corner.radius.max=max: 100
googlepay.size.label=Choose a size:
googlepay.size.option.static=static
googlepay.size.option.fill=fill
googlepay.saved.title=Google Pay Button configuration successfully saved for {0}

loader.text=Loading...

cwpp.title=Connect with PayPal Button Configuration
cwpp.saved.title=Connect with PayPal Button configuration successfully saved for {0}

cwpp.theme.label=Choose a theme:
cwpp.theme.option.blue=blue
cwpp.theme.option.neutral=neutral

cwpp.location.label=Choose a location:
cwpp.location.option.billing=billing
cwpp.location.option.login=login

cwpp.buttonType.label=Choose a label:
cwpp.buttonType.option.connectwithpaypal=Connect with PayPal
cwpp.buttonType.option.loginwithpaypal=Log in with PayPal

cwpp.buttonShape.label=Choose a shape:
cwpp.buttonShape.option.rect=rect
cwpp.buttonShape.option.pill=pill

cwpp.buttonSize.label=Choose a size:
cwpp.buttonSize.alert.message=The size changes are visible only in Drop-in on the storefront
cwpp.buttonSize.option.small=small
cwpp.buttonSize.option.medium=medium
cwpp.buttonSize.option.large=large
cwpp.buttonSize.option.responsive=responsive

cardfields.title=Card Fields Style Configuration
cardfields.note=Note: To test error cases, you should use card (1111 1111 1111 1111) and date (11 / 11)

cardfields.example.name=Cardholder name
cardfields.example.card=Card number
cardfields.example.cvv=CVV
cardfields.example.expiration=Expiration date

cardfields.example.placeholder.card=4111 1111 1111 1111
cardfields.example.placeholder.cvv=•••
cardfields.example.placeholder.expiration=MM/YY

cardfields.configuration.color=Color:
cardfields.configuration.invalidcolor=Invalid Color Highlight:
cardfields.configuration.validcolor=Valid Color Highlight:
cardfields.configuration.fontsize=Font Size:

cardfields.configuration.value.minsize=min: 8
cardfields.configuration.value.maxsize=max: 16

cardfields.saved.title=Card Fields configuration successfully saved
