disputes.title=PayPal Disputes
disputes.info=This page allows you to view PayPal disputes and use filters for fast searches.
disputes.note=Please, note in order to manage disputes you should use the PayPal Resolution Center.
disputes.notfound=No available disputes

dispute.statistics=Dispute statistics (by status)
dispute.view.details=View Details
dispute.resolutioncenter=Go to PayPal Resolution Center

dispute.label.id=Dispute ID
dispute.label.createtime=Create Time
dispute.label.updatetime=Update Time
dispute.label.reason=Dispute Reason
dispute.label.status=Status
dispute.label.amount=Dispute Amount
dispute.label.details=Dispute Details
dispute.label.manage=Manage Dispute

dispute.search=Search Dispute
dispute.search.id=Dispute ID:
dispute.search.status=Dispute Status:
dispute.search.reason=Dispute Reason:
dispute.search.by.id=By Dispute ID
dispute.search.by.status=By Dispute Status
dispute.search.by.reason=By Dispute Reason

dispute.detail.title=Dispute ID: {0}
dispute.detail.amount=Disputed Amount
dispute.detail.reason=Dispute Reason
dispute.detail.status=Dispute Status
dispute.detail.buyer.requestedamount=Buyer Requested Amount
dispute.detail.seller.offeredamount=Seller Offered Amount
dispute.detail.seller.offertype=Seller Offer Type
dispute.detail.buyer.responseduedate=Buyer Response Due Date
dispute.detail.seller.responseduedate=Seller Response Due Date
dispute.detail.lifecyclestage=Dispute Lifecycle Stage
dispute.detail.channel=Dispute Chanel
dispute.detail.outcome=Dispute Outcome
dispute.detail.amountrefunded=Amount Refunded
dispute.detail.evidences.title=Dispute Evidences
dispute.detail.evidence.type=Type
dispute.detail.evidence.source=Source
dispute.detail.evidence.notes=Notes
dispute.detail.history.title=Dispute History
dispute.detail.history.note=Please note that dispute may not contain the full dispute history.
dispute.detail.history.time=Timestamp
dispute.detail.history.status=Status
dispute.detail.history.amount=Amount
dispute.detail.messages.title=Messages Related to the Dispute
dispute.detail.no.messages=No messages
dispute.detail.message.time=Time
dispute.detail.message.initiator=Initiator
dispute.detail.message.content=Content
dispute.detail.seller.transactionid=Seller Transaction ID
dispute.detail.buyer.transactionid=Buyer Transaction ID
dispute.detail.transaction.paymentstatus=Transaction Payment Status
dispute.detail.transaction.createtime=Transaction Create Time
dispute.detail.transaction.amount=Transaction Amount
dispute.detail.invoicenumber=Invoice Number
dispute.detail.seller.name=Seller Name
dispute.detail.seller.email=Seller Email
