test.connection.notification.success=Connection with PayPal is successful.
test.connection.notification.failure=Connection with PayPal failed! Please check your service configurations in Business Manager (Administration/Services).
