checkbox.logs.label=PayPal plugin logs
checkbox.services.label=List of services added to Business Manager
checkbox.connection.label=Test connection with PayPal
checkbox.paymentmethods.label=Payment methods that are enabled in the Business Manager
checkbox.customsitepreferences.label=Custom site preferences

button.generate.config=Generate Plugin Configuration
button.test.connection=Test connection with PayPal
button.test.flows=Self-Check

preference.incorrect.groupid={0} group not found

common.label.search.by.id=Search by ID
common.label.instance.type=Instance Type
common.label.default.indicator=(default)
common.label.site=Site

common.instanceType.label.sandbox=Sandbox
common.instanceType.label.staging=Staging
common.instanceType.label.production=Production

common.button.find=Find
common.button.save=Save
common.button.cancel=Cancel
common.button.add=Add
common.button.back=Back
common.button.next=Next
common.button.apply=Apply
common.button.ok=Ok
common.button.apply.to.sites=Apply to Other Sites
common.button.select.all=Select all

common.column.name=Name
common.column.value=Value
common.column.default.value=Default Value
common.column.property.description=Property Description

common.option.label.no=No
common.option.label.yes=Yes
common.option.label.none=None

common.wizard.selection.pref=Preference Selection
common.wizard.selection.site=Site Selection
common.wizard.summary=Summary
common.wizard.alert.label=Unsaved Changes
common.wizard.alert.message=There are unsaved changes. If you continue, you will lose all your changes. Are you sure you want to continue?

configcheck.modal.title=Generate Plugin Configurations
configcheck.modal.text=Please select the plugin configurations which will be generated into the zip file:
configcheck.modal.alert=Please follow the PayPal integration guide in order to properly configure and use this functionality.
configcheck.modal.status.testconnection=Test connection with PayPal
configcheck.modal.status.export=Export site metadata
configcheck.modal.status.process=File processing
configcheck.export.success=The selected Plugin Configurations were successfully exported. Please note that files may contain some sensitive data. Please review the files and mask all the sensitive data before sharing it.
configcheck.export.failure=The export of selected Plugin Configurations failed. Try again later.
configcheck.export.general.success=The general plugin information was successfully exported.
configcheck.export.some.failure=The selected Plugin Configurations were successfully exported. Please note that files may contain some sensitive data. Please review the file and mask all the sensitive data before sharing it. Please pay attention that the following file(s): {0} were not successfully processed due to the errors.
configcheck.export.testconnection.failure=Connection with PayPal failed and the connection status is exported to the file! Please check your service configuration in Business Manager (Administration/Services).

selfcheck.modal.title=Configuration check
selfcheck.modal.head=List of flows
selfcheck.modal.note=Verification of business flows correctness will be conducted. Results will contain information regarding possible configuration mistakes.
selfcheck.modal.checkbox.all=Check All
selfcheck.modal.checkbox.label.service=Service: {0}

input.exportfile.label=Export file to:
input.filename.title=The file name must contain at least 5 alphanumeric characters (letters, numbers), underscores or hyphens, ending with '.zip'

note.paymentmethod.disabled=Note: The changes on the {0} Configuration tab cannot be applied since this payment method is disabled.
note.paymentmethod.fastlane.disabled.paypal=Please note: Fastlane by PayPal Checkout is disabled since PayPal payment method is deactivated.
note.paymentmethod.fastlane.disabled.creditcard=Please note: Fastlane by PayPal Checkout is disabled since PayPal Credit Card payment method is deactivated.
note.paymentmethod.fastlane.disabled.both=Please note: Fastlane by PayPal Checkout is disabled since PayPal and PayPal Credit Card payment methods are deactivated.
common.message.NoResultsMessage=No results could be found. Please enter a new search term in the search box above.
common.message.NoRecordsExistMessage=This group doesn't have any preferences assigned to it. Use the Site Development module to create preference types for this group.
