# Match against SOMConstants
msg.placed.order.update=Order Update

subject.order.ORDER_STATUS_OPEN.email=Order {0} opened.
subject.order.ORDER_STATUS_COMPLETED.email=Order {0} completed.
subject.order.ORDER_STATUS_CANCELLED.email=Order {0} cancelled.
subject.order.ITEM_STATUS_ORDERED.email=Order {0} item ordered.
subject.order.ITEM_STATUS_RETURNED.email=Order {0} item returned.
subject.order.ITEM_STATUS_CANCELED.email=Order {0} item cancelled.
subject.order.ITEM_STATUS_PAID.email=Order {0} item paid.
subject.order.ITEM_STATUS_RESHIPPED.email=Order {0} item reshipped.
subject.order.ITEM_STATUS_FULFILLED.email=Order {0} item fulfilled.
subject.order.ITEM_STATUS_FULFILLED.WITH_TRACKING.email=Order {0} new tracking information.
subject.order.ITEM_STATUS_PARTIALLYFULFILLED.email=Order {0} item partially fulfilled.
subject.order.ITEM_STATUS_ALLOCATED.email=Order {0} item allocated.
subject.order.ITEM_STATUS_PARTIALLYALLOCATED.email=Order {0} item partially allocated.

label.status=Status
label.trackingno=Tracking Number:
value.trackingno={0} {1}
status.ORDER_STATUS_OPEN=Opened
status.ORDER_STATUS_COMPLETED=Completed
status.ORDER_STATUS_CANCELLED=Cancelled
status.ITEM_STATUS_ORDERED=Ordered
status.ITEM_STATUS_RETURNED=Returned
status.ITEM_STATUS_CANCELED=Cancelled
status.ITEM_STATUS_PAID=Paid
status.ITEM_STATUS_RESHIPPED=Reshipped
status.ITEM_STATUS_FULFILLED=Fulfilled
status.ITEM_STATUS_PARTIALLYFULFILLED=Partially Fulfilled
status.ITEM_STATUS_ALLOCATED=Allocated
status.ITEM_STATUS_PARTIALLYALLOCATED=Partially Allocated
