##############################################
# Directory: forms
##############################################
error.message.500orless=Must be 500 characters or less.
error.message.username.invalid=Username already exists.
error.message.passwordRequirements=Password must contain a number and an uppercase letter. Minimum length 6 characters.
helper.message.passwordRequirements=Password must contain:
helper.message.passwordRequirementsCapitalized=PASSWORD MUST CONTAIN:
requirement.message.length=8
helper.message.length=Minimum length of 8 characters
helper.message.number=At least one number
helper.message.special=At least one special character
helper.message.uppercase=At least one uppercase letter
helper.message.lowercase=At least one lowercase letter

##############################################
# Template name: forms/profile
##############################################
error.message.parse.name.invalidChars=Only alphabetic characters are allowd

##############################################
# Template name: forms/address
##############################################
address.phone.regex=^[\\\d\+\(\) \-]\+$
address.email.regex=^\\\w+([-+.']\\\w+)*@\\\w+([-.]\\\w+)*\\\.\\\w+([-.]\\\w+)*$
address.postalcode.regex=^\\\d{5}(-\\\d{4})?$)|(^[abceghjklmnprstvxyABCEGHJKLMNPRSTVXY]{1}\\\d{1}[A-Za-z]{1} *\\\d{1}[A-Za-z]{1}\\\d{1}$

##############################################
# Template name: forms/giftcertificate
##############################################
giftcertificate.purchase.from.label=Your Name
giftcertificate.purchase.from.missing-error=Please enter your name.
giftcertificate.purchase.recipient.label=Friend's Name
giftcertificate.purchase.recipient.missing-error=Please enter your friend's name.
giftcertificate.purchase.recipientemail.label=Friend's Email
giftcertificate.purchase.recipientemail.parse-error=The email address is invalid.
giftcertificate.purchase.recipientemail.missing-error=Please enter your friend's email.
giftcertificate.purchase.recipientemail.value-error=Please enter your friend's email.
giftcertificate.purchase.confirmrecipientemail.label=Confirm Friend's Email
giftcertificate.confirmrecipientemailparseerror=The email address is invalid.
giftcertificate.confirmrecipientemailmissingerror=Please confirm your friend's email.
giftcertificate.confirmrecipientemailvalueerror=The email address doesn't match your friend's email.
giftcertificate.balance.giftcertificateid.label=Gift Certificate Code
giftcertificate.balance.giftcertificateid.missing-error=Please enter a valid Gift Certificate.
giftcertificate.messagelabel=Message
giftcertificate.purchasemessagedescription=
giftcertificate.amountlabel=Amount
giftcertificate.amountdescription=
giftcertificate.amountparseerror=Gift Certificate can only be purchased in whole number increments
giftcertificate.amountmissingerror=Gift Certificate can only be purchased with a specified amount
giftcertificate.amountvalueerror=Gift Certificate can only be purchased with a minimum of {0} and maximum of {1}

##############################################
# Account Form
##############################################
description.checkbox.emailsignup.profile=Please add me to the What Goes Around Comes Around email list.
description.checkbox.emailsignup.promotions=Stay up to date with new arrivals & promotions via email

description.checkbox.getExclusiveOffers = Get exclusive offers & restock alerts texted right to your phone

##############################################
# Create Account Form
##############################################

label.input.phone.register.profile= Phone Number
example.register.phone = Enter phone number
