###################################################
# Homepage - strings
###################################################
description.form.emailsignup=Stay in the know
button.form.emailsignup=Sign up
placeholdertext.form.emailsignup=Enter your email
subscribe.email.invalid=Please enter a valid email address
subscribe.email.success=Success! You're subscribed to our newsletter
