newslettersubscriber.js.signup.success.msg=You have been added to the WGACA email list
newslettersubscriber.js.invalid.email.error.msg=Enter valid email
newslettersubscriber.js.duplicate.email.error.msg=Email already exists in the WGACA email list
newslettersubscriber.js.signup.error.msg=Failed to add email in the WGACA email list