##############################################
# PDP text contents
# ${Resource.msg('', 'pdpcontent', null)}
##############################################
pdp.copylink.text=Copy Link
pdp.storeavailable.text=Available At:
pdp.conditionscale.text=Condition Scale
pdp.conditionscale.exit=&times;
pdp.condition.pristine.details=PRISTINE
pdp.condition.pristine.desc=Items with no visible signs of wear. Often brand new or unused.
pdp.condition.excellent.details=EXCELLENT
pdp.condition.excellent.desc=Items with minimal signs of wear that are not easily detectable and overall minor or faint in severity.
pdp.condition.verygood.details=Very Good
pdp.condition.verygood.desc=Items with a few visible signs of wear that are detectable upon close inspection and overall light or moderate in severity.
pdp.condition.good.details=Good
pdp.condition.good.desc=Items with widespread signs of wear that visibly affect multiple areas of the item.
pdp.store.modal.title=Store Details
pdp.store.modal.exit=&times;
pdp.store.modal.address.text=Address
pdp.store.modal.phone.text=Phone
pdp.store.modal.hours.text=Hours
pdp.myaccount.text= My Account

# Store Modal
pdp.store.address.direction.text=Get Directions
#Wooster
pdp.store.address.wooster.address1=113 WOOSTER STREET
pdp.store.address.wooster.address2=NEW YORK, NY 10012
pdp.store.address.wooster.gmap=https://maps.app.goo.gl/VhvCEmeMJ7XZ28Ua9
pdp.store.address.wooster.phone=646-807-4517
#Beverly
pdp.store.address.beverly.address1=9520 Brighton Way
pdp.store.address.beverly.address2=Beverly Hills, CA 90210
pdp.store.address.beverly.gmap=https://maps.app.goo.gl/jihSuGmvxQPgNtcb9
pdp.store.address.beverly.phone=310-858-0250
#Soho
pdp.store.address.soho.address1=351 WEST BROADWAY
pdp.store.address.soho.address2=NEW YORK, NY 10013
pdp.store.address.soho.gmap=https://maps.app.goo.gl/tXtzZBfFtYzdnRnz8
pdp.store.address.soho.phone=212-343-1225
#exceptions
pdp.store.address.exception=No Location found
pdp.store.phone.exception=No Contact found

#Accordions
pdp.accordion.description.head=Description
pdp.accordion.measurement.head=Measurements
pdp.accordion.details.head=Details
pdp.accordion.shipping.head=Shipping & Returns
