recentlyviewed.addtorecentlyviewed.success.msg=The product has been added as recently viewed.
recentlyviewed.addtorecentlyviewed.error.msg=The product could not be added to recently viewed.
recentlyviewed.getproduct.error.msg=Failed to fetch product details.