## cartridge.properties for cartridge plugin_commercepayments
#Wed Oct 21 2020 12:59:27 GMT-0400 (Eastern Daylight Time)
demandware.cartridges.plugin_commercepayments.multipleLanguageStorefront=true
demandware.cartridges.plugin_commercepayments.id=plugin_commercepayments
