form.newsletter.email.optin=Sign me up for the {0} newsletter
form.marketing.email.subscription.header.marketingcloud= Marketing Emails

form.marketing.your.email=Your Email
form.marketing.help.text.enter.email=Enter your email to update your Email Preferences
form.marketing.button.update.email=Update Email
form.marketing.button.submit.email=Submit Email

form.marketing.unsubscribe.all=Unsubscribe All
form.marketing.unsubscribe.from.all.emails=Unsubscribe from all emails

form.marketing.subscription.success=Successfully subscribed.

form.marketing.email.subscription.subscribed= Successfully subscribed to {0}.
form.marketing.email.subscription.unsubscribed= Successfully unsubscribed from {0}.
