email.paymentMethod.CreditCard = Credit Card
email.paymentMethod.GiftCertificate = Gift Certificate
email.paymentMethod.ApplePay = Apple Pay
email.paymentMethod.PayPal = PayPal
email.paymentMethod.Affirm = Affirm
email.paymentMethod.SalesForcePayments = SalesForce Payments
