## cartridge.properties for cartridge plugin_authorize_net
#Thu Jun 07 11:20:48 EDT 2018
demandware.cartridges.plugin_authorize_net.id=plugin_authorize_net
demandware.cartridges.plugin_authorize_net.multipleLanguageStorefront=true
