version=23.4.0
globale.switcher.shippingto=Shipping to
product.restriction=This product is restricted for shipping in the selected shipping country
product.restricted=Due to shipping restrictions, this product is not available.
product.forbidden=Due to shipping restrictions, this product is not available.
product.restriction.label=Restriction
order.dutiesandtaxes.label=Duties, Taxes & Fees
order.paymentMethod.giftCard=Gift Card
order.paymentMethod.loyaltyCard=Loyalty Card
checkout.errorcode.100=ErrorCode 100: An internal error has occurred. Please try again later. We are sorry for the inconvenience.
checkout.errorcode.101=ErrorCode 101: Stock Validation is failed. Please try again later. We are sorry for the inconvenience.
checkout.errorcode.200=ErrorCode 200: An unexpected external error has occurred. Please try again later. We are sorry for the inconvenience.
checkout.errorcode.300=ErrorCode 300: An error has occurred while creating an Order. Please contact support team. We are sorry for the inconvenience.
checkout.errorcode.400=ErrorCode 400: Session of the Checkout is not valid any more. Either Order (in CREATED status) or Basket can not be found.
checkout.errorcode.401=ErrorCode 401: Basket cannot be restored. Please try again later. We are sorry for the inconvenience.
checkout.errorcode.402=ErrorCode 402: Basket is not found. Please try again later.
checkout.errorcode.500=ErrorCode 500: Cart Hash does not match.
checkout.errorcode.600=ErrorCode {0}: An unexpected external error has occurred. Please try again later. We are sorry for the inconvenience.
order.deliveryfromto={0}-{1} Business Days
# General Global-e Order Payload Error, error exception
order.errorcode.100=Unexpected error has occurred: {0}
order.errorcode.101=Empty Payload Data
order.errorcode.102=Payload cannot be parsed
order.errorcode.103=Global-e ErrorCode: {0}
# SFCC Order, MerchantOrderId, MerchantGUID is missing
order.errorcode.104=Payload is not valid or MerchantOrderId or Globale OrderId cannot be found in Payload
order.errorcode.105=Payload is not valid or MerchantGUID cannot be found in Payload!
order.errorcode.106=Payload MerchantGUID not matching! Payload MerchantGUID is : {0} and SFCC MerchanGUID is {1}
order.errorcode.107=Cannot find SFCC Order {0}! Global-e Order {1}
order.errorcode.108=Basket has been already expired!
# Global-e Order Client Create Error
order.errorcode.109=Basket hash does not match: Requested Hash = {0}, calculated Basket Hash = {1}
order.errorcode.110=Order Create Error! Review of exception: {0}
order.errorcode.111=Order Create Flow is set (Site Preference: Order Create Flow) to create SFCC Order before Global-e Checkout!
# Send Order to Merchant Errors
order.errorcode.200=Payload is not valid or PrimaryBilling cannot be found in Payload!
order.errorcode.201=order.setCustomerName(...) Error: {0}
order.errorcode.202=An Error occurred while stored Delivery Store ID: {0}
order.errorcode.203=Shipping Method Error: {0}
order.errorcode.204=Global-e Basic Attributes Error: {0}
order.errorcode.205=Payload is not valid or Global-e Order Number cannot be found in Payload!
order.errorcode.206=Payload is not valid or Global-e Currency Code cannot be found in Payload!
order.errorcode.207=Global-e Loyalty Data error
order.errorcode.208=Payload is not valid or Global-e International Details cannot be found in Payload!
order.errorcode.209=Global-e InternationalDetails Error {0}
order.errorcode.210=Global-e Order or Customer Address Error: {0}
order.errorcode.211=Payload is not valid or Global-e Primary Billing Address cannot be found in Payload!
order.errorcode.212=Payload is not valid or Global-e Primary Shipping Address cannot be found in Payload!
order.errorcode.213=Global-e Address Attributes Error: {0}
order.errorcode.214=Payload is not valid or Global-e PrimaryShipping.Email cannot be found in Payload!
order.errorcode.215=Payload is not valid or Global-e Customer.EmailAddress cannot be found in Payload!
order.errorcode.216=Global-e Customer Comments Error {0}
order.errorcode.217=Global-e Products Error {0}
order.errorcode.218=Payload is not valid or Global-e Products cannot be found in Payload!
order.errorcode.219=SFCC Order.allProductLineItems is empty!
order.errorcode.220=Payload is not valid or Global-e Product.Quantity cannot be found in Payload!
order.errorcode.221=Payload is not valid or Global-e Product.VATRate cannot be found in Payload!
order.errorcode.222=Payload is not valid or Global-e Product.InternationalPrice and Product.InternationalDiscountedPrice cannot be found in Payload!
order.errorcode.223=Payload is not valid or Global-e Product.Price cannot be found in Payload!
order.errorcode.224=Payload is not valid or Global-e Product.Sku cannot be found in Payload!
order.errorcode.225=Can not find Order.productLineItem: {0}
order.errorcode.226=Global-e PriceAdjustments Error {0}
order.errorcode.227=Payload is not valid or Global-e Discount.VATRate cannot be found in Payload!
order.errorcode.228=Payload is not valid or Global-e Discount.Price cannot be found in Payload!
order.errorcode.229=Payload is not valid or Global-e Discount.DiscountType cannot be found in Payload!
order.errorcode.230=Payload is not valid or Global-e Discount.InternationalPrice cannot be found in Payload!
order.errorcode.231=Cannot find ProductLineItem by position: {0}
order.errorcode.232=Cannot place Order! Error: {0}
order.errorcode.234=Global-e Mixed Orders Attributes Error: {0}
order.errorcode.235=Global-e Order Type Attribute Error: {0}
# Perform Payment Errors
order.errorcode.300=Set PaymentAttributes Error {0}
order.errorcode.301=Payload is not valid or Global-e PaymentDetails cannot be found in Payload!
order.errorcode.302=Set PaymentInstrument(s) Error {0}
order.errorcode.303=Get Payment Method Error: {0}
order.errorcode.304=SFCC Order is not valid. TotalGrossPrice is not available!
order.errorcode.305=Create PaymentInstrument Error: {0}
order.errorcode.306=Get Payment Processor Error: {0}
order.errorcode.307=Create Payment Transaction Error: {0}
order.errorcode.308=Set Order Export/Payment status Error: {0}
# Order Status Update Errors
order.errorcode.400=Global-e Order Status Update Error: {0}
order.errorcode.401=Global-e StatusCode cannot be found in Payload!
order.errorcode.402=Order cannot be CANCELLED in the following status: {0}
order.errorcode.403=Order cannot be FAILED in the following status: {0}
order.errorcode.404=Order cannot be FAILED! Error: {0}
order.errorcode.405=The Order Status {0} is not supported by SFCC!
# Shipping Status Update Errors
order.errorcode.500=Global-e Order Shipping Status Update Error: {0}
# Refund Notification Errors
order.errorcode.600=Global-e Refund Notification Error: {0}
order.errorcode.601=Global-e RefundId cannot be found in Payload!
order.errorcode.602=Global-e TotalRefundAmount cannot be found in Payload!
order.errorcode.603=Global-e Components and Products cannot be found in Payload!
order.errorcode.604=Global-e OriginalTotalRefundAmount cannot be found in Payload!
order.errorcode.605=Global-e Merchant.RefundProduct.CartItemId cannot be found in Payload!
order.errorcode.606=Global-e Merchant.RefundProduct.RefundQuantity cannot be found in Payload!
order.errorcode.607=Global-e Merchant.RefundProduct.OriginalRefundAmount cannot be found in Payload!
order.errorcode.608=Global-e Merchant.RefundProduct.RefundAmount cannot be found in Payload!
order.errorcode.609=Global-e Merchant.RefundComponent.Amount cannot be found in Payload!
order.errorcode.610=Global-e Merchant.RefundComponent.OriginalAmount cannot be found in Payload!
# RMA Errors
order.errorcode.700=RMA Error: {0}
########## Order History
order.orderdetails.tracking=Order Tracking
order.orderdetails.trackingnumber=Tracking Number: {0}
order.orderdetails.shippingmethod={0}