/* Helper functions for when working with feed data and jobs. */
'use strict';

var ProductInfoKeys = require('~/cartridge/scripts/constants/FeedConstants').ProductInfoKeys;

exports.GetEmptyProductInfo = getEmptyProductInfo;
exports.PopulateProductInfoForFeed = populateProductInfoForFeed;
exports.GetHeaderRow = getHeaderRow;
exports.GetValuesRow = getValuesRow;
exports.GetAllSiteProducts = getAllSiteProducts;

/* ***** Public Functions ***** */
/**
 * Creates an empty JSON object with attributes for all the standard
 * and custom product attributes (using the given customProductAttributeIds)
 * @param {String} customProductAttributeIds: A comma separated list of the custom product attribute ids
 * @returns {Object} An empty JSON object ready to be populated with product data
 */
function getEmptyProductInfo(customProductAttributeIds) {
	var productInfoContainer = {};
	var keys = Object.keys(ProductInfoKeys);
	for (var index = 0; index < keys.length; index++) {
		productInfoContainer[keys[index]] = '';
	}

	var customKeys = customProductAttributeIds.split(',');
	for (var customIndex = 0; customIndex < customKeys.length; customIndex++) {
		productInfoContainer[customKeys[customIndex]] = '';
	}

	return productInfoContainer;
}

/**
 * Using the given product object and info from the jobParameters,
 * populates the productInfo object with data that will be written to the feed file.
 * @param {dw.catalog.Product} product - A SFCC Product system object
 * @param {Object} productInfo: A JSON object to hold product data to be written to the feed file
 * @param {Object} jobParameters: A JSON object with the parameters passed in from the job
 */
function populateProductInfoForFeed(product, productInfo, jobParameters) {
	var priceInfos = getPriceInfos(product);
	var allVariationInfos = getAllVariationInfos(product);

	productInfo[ProductInfoKeys.ProductId] = product.ID;
	productInfo[ProductInfoKeys.ProductName] = product.name || '';
	productInfo[ProductInfoKeys.MasterProductId] = getMasterProductId(product);
	productInfo[ProductInfoKeys.Brand] = product.brand || '';
	addPrimaryAndClassificationCategories(product, productInfo);
	productInfo[ProductInfoKeys.IsBundle] = product.bundle.toString();
	productInfo[ProductInfoKeys.InventoryQuantity] = getInventoryQuantity(product);
	productInfo[ProductInfoKeys.InventoryInStockDate] = getInventoryInStockDate(product);
	productInfo[ProductInfoKeys.AvailabilityStatus] = getAvailabilityStatus(product);
	productInfo[ProductInfoKeys.IsOrderable] = getIsOrderable(product);
	var regularPrice = getPrice(priceInfos, jobParameters.RegularPriceBookId);
	productInfo[ProductInfoKeys.RegularPrice] = regularPrice > 0 ? regularPrice : '';
	var salesPrice = getSalesPrice(product, regularPrice);
	productInfo[ProductInfoKeys.SalesPrice] = salesPrice;
	addOtherPrices(priceInfos, jobParameters, productInfo);
	productInfo[ProductInfoKeys.Variations] = allVariationInfos;
	productInfo[ProductInfoKeys.PageTitle] = product.pageTitle || '';
	productInfo[ProductInfoKeys.PageDescription] = product.pageDescription || '';
	productInfo[ProductInfoKeys.Online] = product.online.toString() || '';
	productInfo[ProductInfoKeys.OnlineFrom] = product.onlineFrom ? product.onlineFrom.toDateString() : '';
	productInfo[ProductInfoKeys.OnlineTo] = product.onlineTo ? product.onlineTo.toDateString() : '';

	productInfo[ProductInfoKeys.ProductDescription] = product.shortDescription ? product.shortDescription.toString() : '';
	var urlUtils = require('dw/web/URLUtils');

	// The url generated by the job in SFCC defaults to the internal Demandware hostname
	// In order to acess it publically, need to change the url to the storefront domain
	var absURL = urlUtils.abs('Product-Show', 'pid', product.ID).toString();
	var system = require('dw/system/System');
	if (system.getInstanceType() === system.PRODUCTION_SYSTEM) {
		absURL = absURL.replace('https://production-na01-whatgoesaroundcomesaround.demandware.net/s/WGACA/', 'https://www.whatgoesaroundnyc.com/');
	} else if (system.getInstanceType() === system.STAGING_SYSTEM) {
		absURL = absURL.replace('https://staging-na01-whatgoesaroundcomesaround.demandware.net/s/WGACA/', 'https://stg.whatgoesaroundnyc.com/');
	} else if (system.getInstanceType() === system.DEVELOPMENT_SYSTEM) {
		absURL = absURL.replace('https://development-na01-whatgoesaroundcomesaround.demandware.net/s/WGACA/', 'https://dev.whatgoesaroundnyc.com/');
	}

	productInfo[ProductInfoKeys.ProductDetailPageUrl] = absURL;
	getProductImages(product, productInfo, jobParameters);
	addCustomAttributes(product, productInfo, jobParameters);
	productInfo[ProductInfoKeys.BackInStockEnabled] = getBackInStockEnabled(product, jobParameters);
}

/**
 * Gets the row of values to be used in the header of the feed file.
 * @param {String} delimiter: The delimiter to use between columns
 * @param {String} customProductAttributeIds: A comma separated list of the custom product attribute ids
 * @returns {String} The header row for the feed file
 */
function getHeaderRow(delimiter, customProductAttributeIds, otherPriceBookInfos) {
	var header = '';
	var keys = Object.keys(ProductInfoKeys);
	// Writes the standard column headers out in the same order as the standard values
	for (var index = 0; index < keys.length; index++) {
		if (index > 0) {
			header += delimiter;
		}
		header += keys[index];
	}

	//  Add additional pricebooks before custom attributes, in the order passed in
	if (otherPriceBookInfos) {
		for (var priceBooksIndex = 0; priceBooksIndex < otherPriceBookInfos.length; priceBooksIndex++) {
			header += delimiter + otherPriceBookInfos[priceBooksIndex].ColumnHeaderValue;
		}
	}

	//  Custom attributes are written last, in the order passed in
	if (customProductAttributeIds) {
		var customKeys = customProductAttributeIds.split(',');
		for (var customIndex = 0; customIndex < customKeys.length; customIndex++) {
			header += delimiter + customKeys[customIndex];
		}
	}

	return header;
}

/**
 * Gets the row of values representing a product for the feed file.
 * @param {String} delimiter: The delimiter to use between columns
 * @param {String} customProductAttributeIds: A comma separated list of the custom product attribute ids
 * @param {Object} productInfo: The JSON object with the product data that will be written to the row for the feed file
 * @returns {String} A row representing a product for the feed file
 */
function getValuesRow(delimiter, customProductAttributeIds, otherPriceBookInfos, productInfo) {
	var valuesRow = '';
	var keys = Object.keys(ProductInfoKeys);
	// Writes the standard data values out in the same order as the standard column headers
	for (var index = 0; index < keys.length; index++) {
		if (index > 0) {
			valuesRow += delimiter;
		}
		var attributeId = keys[index];
		if (attributeId === ProductInfoKeys.Variations) {
			valuesRow += getVariationValues(productInfo[attributeId]);
		} else {
			valuesRow += getSafeValue(productInfo[attributeId]);
		}
	}

	//  Add additional pricebooks before custom attributes, in the order passed in
	if (otherPriceBookInfos) {
		for (var priceBooksIndex = 0; priceBooksIndex < otherPriceBookInfos.length; priceBooksIndex++) {
			var headerValue = otherPriceBookInfos[priceBooksIndex].ColumnHeaderValue;
			valuesRow += delimiter + getSafeValue(productInfo[headerValue]);
		}
	}

	//  Custom attributes are written last, in the order passed in
	if (customProductAttributeIds) {
		var customKeys = customProductAttributeIds.split(',');
		for (var customIndex = 0; customIndex < customKeys.length; customIndex++) {
			valuesRow += delimiter + getSafeValue(productInfo[customKeys[customIndex]]);
		}
	}

	return valuesRow;
}

/**
 * Querys all site products and converts the result to two ArrayLists (variants and masters)
 * then the two ArrayLists are either concated with master products first or just variants
 * @param {boolean} includeMasterProducts: An argument passed in from the job
 * @returns {ArrayList} An ArrayList of product objects
 */
 function getAllSiteProducts(includeMasterProducts) {
	var collections = require('*/cartridge/scripts/util/collections');
	var ArrayList = require('dw/util/ArrayList');
	var allSiteMasterProducts = new ArrayList();
	var allSiteVariantProducts = new ArrayList();

	var ProductMgr = require('dw/catalog/ProductMgr');
	var allSiteProducts = ProductMgr.queryAllSiteProducts();

	while (allSiteProducts.hasNext()) {
		var product = allSiteProducts.next();

		if (product.isVariant()) {
			allSiteVariantProducts.add(product);
		} else {
			allSiteMasterProducts.add(product);
		}
	}

	var orderedSiteProducts = allSiteVariantProducts;

	if (includeMasterProducts === true) {
		orderedSiteProducts = collections.concat(allSiteMasterProducts, allSiteVariantProducts);
	}

	return orderedSiteProducts;
}

/* ***** Private Functions ***** */
function getMasterProductId(product) {
	if (product.isVariant()) {
		if (product.variationModel !== null) {
			var masterProduct = product.variationModel.getMaster();
			if (masterProduct !== null) {
				return masterProduct.ID;
			}
		}
	} else if (product.isMaster() || product.isProduct()) {
		return product.ID;
	}

	return '';
}

/**
 * Populates the productInfo object with the product's primary and classification category info
 * @param {dw.catalog.Product} product - A SFCC Product system object
 * @param {Object} productInfo: The JSON object the product data will be added to
 */
 function addPrimaryAndClassificationCategories(product, productInfo) {
	var primaryCategory = getPrimaryCategory(product);
	if (!empty(primaryCategory)) {
		productInfo[ProductInfoKeys.PrimaryCategory] = primaryCategory;
	}

	var classificationCategory = getClassificationCategory(product);
	if (!empty(classificationCategory)) {
		productInfo[ProductInfoKeys.ClassificationCategory] = classificationCategory;
	}

	if (product.isVariant()) {
		if (product.variationModel !== null) {
			var masterProduct = product.variationModel.getMaster();
			if (empty(primaryCategory)) {
				if (masterProduct !== null) {
					productInfo[ProductInfoKeys.PrimaryCategory] = getPrimaryCategory(masterProduct);
				}
			}
			if (empty(classificationCategory)) {
				if (masterProduct !== null) {
					productInfo[ProductInfoKeys.ClassificationCategory] = getClassificationCategory(masterProduct);
				}
			}
		}
	}
}

function getPrimaryCategory(product) {
	if (product.primaryCategory !== null && !empty(product.primaryCategory.displayName)) {
		return product.primaryCategory.displayName;
	}

	return '';
}

function getClassificationCategory(product) {
	if (product.classificationCategory !== null && !empty(product.classificationCategory.displayName)) {
		return product.classificationCategory.displayName;
	}

	return '';
}

/**
 * Retrieves the inventory quantity from the inventory record and returns
 * a large value in the case of perpetual inventory.
 * @param {dw.catalog.Product} product - A SFCC Product system object
 * @returns {String} The inventory quantity as a string
 */
function getInventoryQuantity(product) {
	if (product.availabilityModel !== null) {
		var inventoryRecord = product.availabilityModel.inventoryRecord;
		if (inventoryRecord !== null) {
			if (inventoryRecord.perpetual) {
				return "99999";
			} else if (inventoryRecord.ATS !== null) {
				return inventoryRecord.ATS.value.toString();
			}
		}
	}

	return "0";
}

/**
 * Retrieves the inventory in stock date from the inventory record, if present.
 * @param {dw.catalog.Product} product - A SFCC Product system object
 * @returns {String} The inventory in stock date as a string
 */
 function getInventoryInStockDate(product) {
	if (product.availabilityModel !== null) {
		if (product.availabilityModel.inventoryRecord && product.availabilityModel.inventoryRecord.inStockDate) {
			return product.availabilityModel.inventoryRecord.inStockDate.toDateString();
		}
	}

	return '';
}

function getAvailabilityStatus(product) {
	if (product.availabilityModel !== null) {
		return product.availabilityModel.availabilityStatus;
	}

	return '';
}

function getIsOrderable(product) {
	if (product.availabilityModel !== null) {
		return product.availabilityModel.orderable.toString();
	}

	return "false";
}

/**
 * Iterates over all the price books assigned to the site this job is running against
 * and retrieves pricing information
 * @param {dw.catalog.Product} product - A SFCC Product system object
 * @returns {Array} An array of JSON objects containing price info on the product
 */
function getPriceInfos(product) {
	var priceBookMgr = require('dw/catalog/PriceBookMgr');
	var priceModel = product.priceModel;
	var allSitePriceBooks = priceBookMgr.getSitePriceBooks().iterator();

	var priceInfos = [];
	while (allSitePriceBooks.hasNext()) {
		var priceBook = allSitePriceBooks.next();
		var priceBookInfo = getPriceBookInfo(priceBook, priceModel);
		priceInfos.push(priceBookInfo);
	}

	return priceInfos;
}

/**
 * Gets the price information for a product from a specific pricebook
 * @param {dw.catalog.PriceBook} priceBook - An SFCC PriceBook system object
 * @param {dw.catalog.ProductPriceModel} priceModel - An SFCC ProductPriceModel system object
 * @returns {Object} - A JSON object containing price info for a specific product and pricebook
 */
function getPriceBookInfo(priceBook, priceModel) {
	var priceBookPrice = priceModel.getPriceBookPrice(priceBook.ID);
	var price = priceBookPrice.decimalValue ? priceBookPrice.decimalValue.toString() : '';

	return {
		'Id': priceBook.ID,
		'CurrencyCode': priceBook.currencyCode,
		'Price': price,
		'ParentPriceBookId': priceBook.parentPriceBook ? priceBook.parentPriceBook.ID : ''
	};
}

function getPrice(priceInfos, priceBookId) {
	for (var index = 0; index < priceInfos.length; index++) {
		if (priceInfos[index].Id === priceBookId) {
			return priceInfos[index].Price;
		}
	}

	return "0";
}

/**
 * Retrieves the sales price for a product based on any product promotions
 * that are available to everyone.
 * @param {dw.catalog.Product} product - A SFCC Product system object
 * @param {String} regularPrice - The regular price as a string
 * @returns A string representation of the Sales Price (or an empty string for master products)
 */
function getSalesPrice(product, regularPrice) {
	var salesPrice = regularPrice ? regularPrice : '';
	if (product.master === false) {
		var productHelper = require('*/cartridge/scripts/helpers/productHelpers');
		var parameters = { pid: product.ID};
		var options = productHelper.getConfig(product, parameters);

		var promotionMgr = require('dw/campaign/PromotionMgr');
		var activeProductPromotions = promotionMgr.activePromotions.getProductPromotions(product);
		var ArrayList = require('dw/util/ArrayList');
		var productPromotionsForAll = new ArrayList();

		for (var index = 0; index < activeProductPromotions.length; index++) {
			var promotion = activeProductPromotions[index];
			if ('IsProductPromotionForEveryone' in promotion.custom && promotion.custom.IsProductPromotionForEveryone) {
				productPromotionsForAll.add(promotion);
			}
		}
		var priceFactory = require('*/cartridge/scripts/factories/price');
		var productPriceInfo = priceFactory.getPrice(product, null, false, productPromotionsForAll, options.optionModel);
		if (productPriceInfo.sales) {
			if (!empty(regularPrice)) {
				var Decimal = require('dw/util/Decimal');
				var regularPriceDecimal = new Decimal(regularPrice);
				if (productPriceInfo.sales.decimalPrice < regularPriceDecimal) {
					salesPrice = productPriceInfo.sales.decimalPrice.toString();
				}
			}
		}
	}

	return salesPrice;
}

/**
 * If other price book ids are passed as job parameters, then this function will
 * look for pricing data for those price books and add to the productInfo object.
 * @param {Array} priceInfos: An array of JSON objects containing pricing data about a product
 * @param {Object} jobParameters: A JSON object with the parameters passed in from the job
 * @param {Object} productInfo: The JSON object the product data will be added to
 * @example An example of how this would be used would be if the job passed in the price book ids
 * for a sale or specific customer group or promotional (seasonal) price book(s)
 */
function addOtherPrices(priceInfos, jobParameters, productInfo) {
	if (jobParameters.OtherPriceBookInfos.length > 0) {
		for (var index = 0; index < jobParameters.OtherPriceBookInfos.length; index ++) {
			var otherPriceBookInfo = jobParameters.OtherPriceBookInfos[index];
			var price = getPrice(priceInfos, otherPriceBookInfo.PriceBookId);
			if (price > 0) {
				productInfo[otherPriceBookInfo.ColumnHeaderValue] = price;
			}
		}
	}
}

/**
 * Gets the specific variation information for a variant product; e.g. Color - Blue, Size - Large
 * or all the variation information for a master product.
 * @param {dw.catalog.Product} product - A SFCC Product system object
 * @returns {Array} - An array of JSON objects containing the variation information for the product
 */
function getAllVariationInfos(product) {
	var variationInfos = [];

	var variationModel = product.getVariationModel();
	var variationAttributes = variationModel ? variationModel.productVariationAttributes : null;
	if (variationAttributes) {
		if (product.isVariant() || product.isVariationGroup()) {
			for (var attributeIndex = 0; attributeIndex < variationAttributes.length; attributeIndex++) {
				var variationAttribute = variationAttributes[attributeIndex];
				var variationValue = variationModel.getVariationValue(product, variationAttribute);
				if (variationValue && !empty(variationValue.displayValue)) {
					variationInfos.push(getVariationInfo(variationAttribute.attributeID, variationValue.displayValue))
				}
			}
		} else if (product.isMaster()) {
			for (var attributeIndex = 0; attributeIndex < variationAttributes.length; attributeIndex++) {
				var variationAttribute = variationAttributes[attributeIndex];
				var variationValues = variationModel.getAllValues(variationAttribute);
				var valueArray = [];
				for (var valueIndex = 0; valueIndex < variationValues.length; valueIndex++) {
					valueArray.push(variationValues[valueIndex].displayValue);
				}
				variationInfos.push(getVariationInfo(variationAttribute.attributeID, valueArray.join(',')));
			}
		}
	}

	return variationInfos;
}

function getVariationInfo(name, value) {
	return {
		'VariationName': name,
		'VariationValue': value
	};
}

/**
 * Retrieves and constructs the absolute URL for the different sizes of the product's default image
 * @param {dw.catalog.Product} product - Product
 * @param {Object} productInfo The JSON object holding the product info for the feed
 * @param {Object} jobParameters: A JSON object with the parameters passed in from the job
 */
 function getProductImages(product, productInfo, jobParameters) {
	var imageTypes = require('~/cartridge/scripts/constants/FeedConstants').ImageTypes;
	productInfo[ProductInfoKeys.ProductImageLarge] = prepareStorefrontImageUrl(getImage(product, imageTypes.Large, jobParameters));
	productInfo[ProductInfoKeys.ProductImageMedium] = prepareStorefrontImageUrl(getImage(product, imageTypes.Medium, jobParameters));
	productInfo[ProductInfoKeys.ProductImageSmall] = prepareStorefrontImageUrl(getImage(product, imageTypes.Small, jobParameters));
}

// The url generated by the job in SFCC defaults to the internal Demandware hostname
// In order to acess it publically, need to change the url to the storefront domain
function prepareStorefrontImageUrl(imagePath) {
	if (imagePath !== null) {
		var system = require('dw/system/System');
		if (system.getInstanceType() === system.PRODUCTION_SYSTEM) {
			imagePath = imagePath.replace('https://production-na01-whatgoesaroundcomesaround.demandware.net/', 'https://www.whatgoesaroundnyc.com/');
		} else if (system.getInstanceType() === system.STAGING_SYSTEM) {
			imagePath = imagePath.replace('https://staging-na01-whatgoesaroundcomesaround.demandware.net/', 'https://stg.whatgoesaroundnyc.com/');
		} else if (system.getInstanceType() === system.DEVELOPMENT_SYSTEM) {
			imagePath = imagePath.replace('https://development-na01-whatgoesaroundcomesaround.demandware.net/', 'https://dev.whatgoesaroundnyc.com/');
		}
	}

	return imagePath;
}

function getImage(product, imageType, jobParameters) {
	var productImage = product.getImage(imageType);
	if (productImage) {
		var hostName = getHostNameValue(product, jobParameters);
		if (!empty(hostName)) {
			return productImage.URL.host(hostName).toString();
		} else {
			return productImage.getAbsImageURL(jobParameters.DISConfigurationJSON[imageType]).toString();
		}
	}

	return '';
}

/** The reason this function was added is because in a multi-brand site configuration
 * 	where there are multiple hostnames configured in the alias settings, the built in
 * 	settings / job-hostnames cannot be used.
 * 	If running this job in a normal single host configuration, that setting can be used
 * 	and the "ProductAttributeHostValueMapping" job parameter can be left blank.
 *  If multiple brand, then that parameter needs to be configured in order for the image URLs
 *  to have the appropriate vanity address.
 */
function getHostNameValue(product, jobParameters) {
	var attributeValue = '';
	if ('Id' in jobParameters.HostValueMapping) {
		if (jobParameters.HostValueMapping.Id in product && !empty(product[jobParameters.HostValueMapping.Id])) {
			attributeValue = product[jobParameters.HostValueMapping.Id].toString();
		} else if (jobParameters.HostValueMapping.Id in product.custom && !empty(product.custom[jobParameters.HostValueMapping.Id])) {
			attributeValue = product.custom[jobParameters.HostValueMapping.Id].toString();
			// NOTE: When using a custom product attribute that is a dw.value.EnumValue,
			// to keep this attributeValue read able and to switch easily to a different attribute
			// a toString() is called, which in the case of an enum, returns the displayValue, as opposed to the value (below)
			// attributeValue = product.custom[jobParameters.HostValueMapping.Id].value;
		}
		if (!empty(attributeValue)) {
			for (var index = 0; index < jobParameters.HostValueMapping.ValueMappings.length; index++) {
				var valueMapping = jobParameters.HostValueMapping.ValueMappings[index];
				if (valueMapping.Value === attributeValue) {
					return valueMapping.Host;
				}
			}
		}
	}

	return '';
}

/**
 * Iterates over the comma delimited list of custom attribute ids passed into the job (if any),
 * retrieves the data for that attribute and adds to the productInfo object.
 * NOTE: This handles string, number, boolean and enum attributes. It does not handle, nor is it recommended to send
 * HTML data to Marketing Cloud.
 * @param {dw.catalog.Product} product - A SFCC Product system object
 * @param {Object} productInfo: The JSON object the product data will be added to
 * @param {Object} jobParameters: A JSON object with the parameters passed in from the job
 */
function addCustomAttributes(product, productInfo, jobParameters) {
	var multipleValueDelimiters = require('~/cartridge/scripts/constants/FeedConstants').MultipleValueDelimiters;
	var customKeys = jobParameters.CustomProductAttributeIds.split(',');
	for (var customIndex = 0; customIndex < customKeys.length; customIndex++) {
		var attributeId = customKeys[customIndex];
		if (Object.hasOwnProperty.call(product.custom, attributeId) && !empty(product.custom[attributeId])) {
			var typeIs = typeof product.custom[attributeId];
			if (typeIs === 'object') {
				if (Object.hasOwnProperty.call(product.custom[attributeId], 'displayValue')) {
					productInfo[attributeId] = product.custom[attributeId].displayValue;
				} else if (product.custom[attributeId].length >=  1){
					var enumValues = '';
					for (var index = 0; index < product.custom[attributeId].length; index++) {
						if (index > 0) {
							enumValues += multipleValueDelimiters.Tilda;
						}
						enumValues += product.custom[attributeId][index].displayValue;
					}
					productInfo[attributeId] = enumValues;
				}
			} else {
				productInfo[attributeId] = product.custom[attributeId];
			}
		}
	}
}

function getBackInStockEnabled(product, jobParameters) {
	if (jobParameters.BackInStockEnabled) {
		if (Object.hasOwnProperty.call(product.custom, 'backInStockNotificationDisabled') && !empty(product.custom.backInStockNotificationDisabled)) {
			if (product.custom.backInStockNotificationDisabled) {
				return "false";
			}
		}

		return "true";
	}

	return "false";
}

function getSafeValue(value) {
	var typeIs = typeof value;
	var encodedValue = '';
	if (typeIs === 'string') {
		encodedValue = value.replace(/\"/g, '&#34;');
		encodedValue = encodedValue.replace(/\r/g, '&#13;');
		encodedValue = encodedValue.replace(/\f/g, '&#12;');
		encodedValue = encodedValue.replace(/\v/g, '&#11;');
		encodedValue = encodedValue.replace(/\n/g, '&#10;');
		encodedValue = encodedValue.replace(/\t/g, '&#09;');
	} else if (typeIs === 'number') {
		encodedValue = value;
	} else if (typeIs === 'boolean') {
		encodedValue = value.toString();
	}

	return "\"" + encodedValue + "\"";
}

function getVariationValues(variationInfos) {
	var multipleValueDelimiters = require('~/cartridge/scripts/constants/FeedConstants').MultipleValueDelimiters;
	var variationValues = '';

	for (var index = 0; index < variationInfos.length; index++) {
		if (index > 0) {
			variationValues += multipleValueDelimiters.Tilda;
		}
		variationValues += variationInfos[index].VariationName + ',' + variationInfos[index].VariationValue;
	}

	return getSafeValue(variationValues);
}
