##############################################
# Directory: checkout/billing
##############################################

##############################################
# Template name: checkout/billing/creditCardForm
##############################################
saveCard.subscription=Required for subscription orders

subpro.buynow.compat.warn=Apple Pay and Google Pay may not be used for subscriptions.
subpro.paypal.compat.warn=PayPal may not be used for subscriptions.
subpro.general.compat.warn=Subscriptions are not supported with this payment method.
