label.payment.ending=Expiration

link.header.login=Sign In
link.header.create=Create Account
link.header.orderhistory=Order History

link.wishlist=Wishlist
link.wishlist.myaccount=Wishlist
link.wishlist.login=Wishlist
label.wishlist=Wishlist
label.wishlists=Wishlists
link.viewall=View All
link.wishlist.alllists.viewall=View All Lists

unavailable.message=Ability to add a saved credit card is not available.

nosavedpayments.message=No payments saved yet.
nosavedpayments.tooltip=Payment methods can be saved during checkout.

savedpayment.default=Default