##############################################
# address/shipping
##############################################
field.shipping.address.select.state=Select State
field.billing.address.select.state=Select State