button.next.payment=Continue to Payment
button.next.place.order=Review Order
button.place.order=Place Order
action.edit.step.msg.customer=Edit Customer

##############################################
# giftcertificate
##############################################
giftcertificate.disabled=Purchase and usage of gift certificates is currently not available
giftcertificate.max.quantity.error=Purchase of gift certificates is limited to {0} per order
giftcertificate.purchase.giftcertificate=Gift Certificate
giftcertificate.purchase.giftcertificates=Gift Certificates
giftcertificate.checkout.applied.quantitydisplay=: (x{0})
giftcertificate.purchase.giftcertificate.edit=Edit Gift Certificate
giftcertificate.purchase.amount=Amount
giftcertificate.checkout.remainingbalance=Remaining Balance
giftcertificate.checkout.apply=Apply Balance
giftcertificate.purchase.errorinfo=Please enter the correct information.
giftcertificate.purchase.balancealert=Your current Gift Certificate balance for {0} is {1}
global.checkbalance=Check Balance
giftcertificate.balance.missing=The gift certificate has a balance of 0, does not exist, or is not active
giftcertificate.balance.wrongcurrency=The gift certificate has a value in {0} and cannot be converted to {1}
giftcertificate.balance.successfullyapplied=The gift certificate has been successfully applied to your cart.
giftcertificate.purchase.addtocart.success.msg=The gift certificate has been added to your cart.
giftcertificate.purchase.updateincart.success.msg=The gift certificate has been updated in your cart.
giftcertificate.checkout.apply.noteligible=A gift certificate cannot be redeemed while also purchasing a new gift certificate
giftcertificate.checkout.remove.doesnotexist=The gift certificate you are trying to remove does not exist.  Please reload the page and try again.
giftcertificate.checkout.remove.success=The gift certificate has been removed from your cart.
giftcertificate.checkout.error.internal=There was a problem adding the gift certificate to your cart.
giftcertificate.checkout.error.internal.remove=There was a problem removing the gift certificate from your cart.
giftcertificate.checkout.error.redeem=There was a problem redeeming the applied gift certificates. Please check the gift certificate code and try again.
email.giftcertificate.msghasbeenleftforyou=has left the following message for you:
email.giftcertificate.msgleftforyou=The following message has been left for you:
email.giftcertificate.toredeem=To redeem your gift certificate, use the following code within the billing step of the checkout:
email.giftcertificate.dearcustomer=Dear customer,
email.giftcertificate.dear=Dear {0},
email.giftcertificate.someone=Someone
email.giftcertificate.paysattention=has sent you a {0} gift certificate for the
email.giftcertificate.dwonlinestore=Salesforce Commerce Cloud Online Store
email.giftcertificate.period=.
email.giftcertificate.ordergcemsg=A gift certificate from

##############################################
# checkout/email summary
##############################################
msg.paid.using.apple.pay=Paid using ApplePay

##############################################
# checkout/shipping
##############################################
shipping.select.state=Select State
heading.shipping.method=Shipping Method:
heading.shipping.to=Shipping To:

multiship.buynow.compat.warn=Apple Pay and Google Pay may not be used for multi ship orders.
giftcertificateincart.cyberpaypal.compat.warn=PayPal may not be used to purchase gift certificates.
giftcertificatepaymentinstrument.cyberpaypal.compat.warn=Partial gift certificates may not be used with PayPal. You will be charged the total amount of {0}.
error.message.taxcalculation.address=The ZIP code entered does not match the selected City and State. Please correct the shipping address to continue.
