label.header.searchwatermark=Search by brand, article...
label.header.searchwatermark.arrow=<
label.play= Play
label.close = Close
global.youtubeThumbnailURL=https://img.youtube.com/vi/{0}/0.jpg
button.quickview.buy=Quickview
button.quickAddtocart= Add product to cart: {0}
button.quickAddtocart.buy=Add to cart
data.content.quickAddtocart=Gathering product info...

label.modal.close=Close
label.modal.dialog.message=View your requested information.
simplesearch.searchtext=Enter Keyword or Item Number

label.increase.quantity=Increase Quantity
label.decrease.quantity=Decrease Quantity

error.recaptcha.fail=Invalid form submission

minicart.count.default=Cart Items
