##############################################
# Directory: forms
##############################################
error.message.500orless=Must be 500 characters or less.
error.message.passwordRequirements=Password must contain a number, special character, and an uppercase letter. Minimum length 8 characters.
helper.message.passwordRequirements=Password must contain:
#requirement.message.length=8
helper.message.length=Minimum length of {0} characters
helper.message.number=At least one number
helper.message.special=At least one special character
helper.message.specials=At least {0} special character
helper.message.letter=At least one letter
helper.message.uppercase=At least one uppercase letter
helper.message.lowercase=At least one lowercase letter

##############################################
# Template name: forms/profile
##############################################
error.message.username.invalid=Username is invalid or account is already registered.

##############################################
# Template name: forms/address
##############################################
address.postalcode.regex=^\\\d{5}(-\\\d{4})?$)|(^[abceghjklmnprstvxyABCEGHJKLMNPRSTVXY]{1}\\\d{1}[A-Za-z]{1} *\\\d{1}[A-Za-z]{1}\\\d{1}$

##############################################
# Template name: forms/giftcertificate
##############################################
giftcertificate.purchase.from.label=Your Name
giftcertificate.purchase.from.missing-error=Please enter your name.
giftcertificate.purchase.recipient.label=Friend's Name
giftcertificate.purchase.recipient.missing-error=Please enter your friend's name.
giftcertificate.purchase.recipientemail.label=Friend's Email
giftcertificate.purchase.recipientemail.parse-error=The email address is invalid.
giftcertificate.purchase.recipientemail.missing-error=Please enter your friend's email.
giftcertificate.purchase.recipientemail.value-error=Please enter your friend's email.
giftcertificate.purchase.confirmrecipientemail.label=Confirm Friend's Email
giftcertificate.confirmrecipientemailparseerror=The email address is invalid.
giftcertificate.confirmrecipientemailmissingerror=Please confirm your friend's email.
giftcertificate.confirmrecipientemailvalueerror=The email address doesn't match your friend's email.
giftcertificate.balance.giftcertificateid.label=Gift Certificate Code
giftcertificate.balance.giftcertificateid.missing-error=Please enter a valid Gift Certificate.
giftcertificate.messagelabel=Message
giftcertificate.purchasemessagedescription=
giftcertificate.amountlabel=Amount
giftcertificate.amountdescription=
giftcertificate.amountparseerror=Gift Certificate may only be purchased in whole number increments
giftcertificate.amountmissingerror=Gift Certificate may only be purchased with a specified amount
giftcertificate.amountvalueerror=Gift Certificate may only be purchased with a minimum of {0} and maximum of {1}
resource.select= Select State
