label.recommendedproducts=Recommended Products
product.tile.swatchcount.colors={0} colors
label.item=no.
button.share=Share
quantity.label=Select quantity:
select.variant.value=Select a {0}
product.option.unavailable= - not available with current selections

label.set.contains=Set contains
label.set.item = product
label.pluralize =s
label.digitalDelivery=Digital
label.deliveryType=Delivery Type

btn.backinstock=Notify me when back in stock
header.backinstock=Get notified when this item is back in stock.
success.backinstock=You will be notified when this item is back in stock.

form.email.placeholder.backinstock= Enter your email
form.email.error.empty=Please enter a valid E-Mail address
form.email.error.fallback=Something went wrong please refresh and try again.

error.alert.choiceofbonus.no.product.selected=You did not select any bonus products to add to the cart. You can finish your selecton on the cart page.

