horizontal.button.filter= Filter By

label.articlefound={0} Article Found
label.articlesfound={0} Articles Found
label.emptyquery=A query was not provided
label.refinement.toggle.menu=Close Refinement Menu
label.resultfor={0} Result for
label.searchfor=Search for "{0}"
label.filter=Filter
label.filter.mb.count=({0})


link.all=All
link.showhide=Show / Hide Filters

sort.error=Something went wrong. Please try again.

tab.nav.search.artclesresults=Articles {0}
tab.nav.search.productsresults=Products {0}
