input.select.allStores=All Stores
label.address=Address
label.storetype=Store Type
label.email=Email
label.phone=Phone
label.hours=Store Hours
label.events=Store Events
label.additionaldetails=Additional Details
link.viewmap=View on Google Maps
no.stores.with.inventory=We're sorry, we couldn't find any stores near this location.
no.stores.with.inventory.for.product=We're sorry, we couldn't find any stores near this location with this product in stock.
error.storelocator.header.set=Failed to save your preferred store
storelocator.header.title=Choose your preferred store
storelocator.header.prompt=My Store
button.storelocator.maps.individual=Set {0} as your home store
