bambuser.title=Bambuser
bambuser.subtitle=Available Streams

bambuser.section.upcoming=Upcoming
bambuser.section.live=Live
bambuser.section.ended=Ended

bambuser.label.startsat=starts {0}
bambuser.label.endedat=ended at {0}
bambuser.label.live=Live!
