## cartridge.properties for cartridge int_flow_sfra
#Wed May 01 2019 11:08:10 GMT-0400 (Eastern Daylight Time)
demandware.cartridges.int_flow_sfra.multipleLanguageStorefront=true
demandware.cartridges.int_flow_sfra.id=int_flow_sfra
