## cartridge.properties for cartridge int_flow
#Wed May 01 2019 11:08:10 GMT-0400 (Eastern Daylight Time)
demandware.cartridges.int_flow.multipleLanguageStorefront=true
demandware.cartridges.int_flow.id=int_flow
