label.card.brand.amex=American Express
label.card.brand.diners=Diners Club
label.card.brand.discover=Discover
label.card.brand.jcb=JCB
label.card.brand.mastercard=MasterCard
label.card.brand.unionpay=UnionPay
label.card.brand.unknown=Unknown
label.card.brand.visa=Visa

label.credential.bancontact={0} account ending in {1}
label.credential.card={0} ending in {1}
label.credential.ideal={0} bank
label.credential.sepa_debit=Account ending in {0}
label.method.bancontact=Bancontact
label.method.card=Credit Card
label.method.ideal=iDEAL
label.method.sepa_debit=SEPA Debit
