## cartridge.properties for cartridge flow_sfra_changes
#Mon Apr 27 11:41:32 EDT 2020
demandware.cartridges.flow_sfra_changes.id=flow_sfra_changes
demandware.cartridges.flow_sfra_changes.multipleLanguageStorefront=true
