## cartridge.properties for cartridge wgaca_stripe_sfra
#Mon May 22 16:52:49 CEST 2026
demandware.cartridges.wgaca_stripe_sfra.multipleLanguageStorefront=true
demandware.cartridges.wgaca_stripe_sfra.id=wgaca_stripe_sfra