photohotspots.tooltip.message=(Click for Quickview)
video.replay=Replay Video
blog.folderid=blogCategories
label.blog.keywords=Keywords:
label.blog.author=Author:
meta.blog.title=Blog
meta.blog.description=The {0} Blog
meta.blog.keywords=blog articles
discountstatusbar.nopromomessage=There are no approaching promotions found.