# cartridge.properties for cartridge rvw_flow_integration
# Wed Oct 27 08:02:23 PDT 2021
demandware.cartridges.rvw_flow_integration.multipleLanguageStorefront=true
demandware.cartridges.rvw_flow_integration.id=rvw_flow_integration
