## cartridge.properties for cartridge int_bambuser
#Thu Jun 09 11:30:40 EDT 2016
demandware.cartridges.int_bambuser.multipleLanguageStorefront=true
demandware.cartridges.int_bambuser.id=int_bambuser
demandware.cartridges.int_bambuser.version=24.1.0

