label.payment.paypal=PayPal
label.payment.creditcards=Paypal Credit Cards
label.payment.expirationdate=Expiration Date

label.profile.cwpp=Login with PayPal
label.profile.unlink=Unlink

label.unlink.heading=Unlink Login with PayPal
label.unlink.info=You are going to unlink a Login with PayPal for this user account. Please ensure that you remember the credentials to your user account.
label.unlink.confirmation=In order to confirm this action please click the OK button, if not please click the Cancel button.
label.unlink.notification=You have successfully unlinked Login with Paypal from your Account
label.unlink.cancel=Cancel
label.unlink.ok=OK

creditcard.notification.expired=Please note that you have a credit card in your wallet that is expired. You will not be able to place the order with this credit card.
creditcard.notification.expiresoon=Please note that you have a credit card in your wallet that is going to expire soon. Please check it.
creditcard.notification.removed=Credit Card has been successfully removed.
creditcard.notification.limit=You reached the maximum number of saved credit cards. In order to save a new credit card please remove the already saved one.

paypal.notification.removed=PayPal Account has been successfully removed.

creditcard.default=(Default)
creditcard.notfound=Credit card not found
creditcard.alreadydefault=Please note, this credit card is already set as your default payment method.
creditcard.setdefault=Card is set as the default

button.creditcard.makedefault=Make default
button.creditcard.makedefault.arialabel=Make default payment
