label.paypal.creditcard.field.cardholder=Cardholder name
label.paypal.creditcard.field.cardNumber=Card number
label.paypal.creditcard.field.cvv=CVV
label.paypal.creditcard.field.expirationdate=Expiration date
