account.legacy=Please note that you already have a legacy user account created via Login with PayPal. If you have some saved records (order history, PayPal payment methods, and addresses), they will be transferred to the current user account and accessible via both Single Authentication login and Login with PayPal. To avoid account duplicates, the legacy user account will be removed.
account.exists=Please note that you are logged in to your existing user account.

email.account.linked.pp.title=Notification: Your Paypal account is linked to your account at {0}
email.account.linked.pp.text=Please note that your pre-existing user account on the webiste {0} is linked to your PayPal account using this email address {1}

email.account.unlinked.pp.title=Notification: Your Paypal account is unlinked from your user account on the webiste {0}
email.account.unlinked.pp.text=Please note that your pre-existing user account on the webiste {0} is unlinked from your PayPal account using this email address {1}

email.alert.dear.user=Dear user,
email.alert.be.informed=Please be informed that you have: {0} transactions with {1} status
email.alert.add.more.content=You can add more content and formatting as needed for your email.
email.alert.please.review=Please review transactions in Business Manager (Merchant Tools > PayPal Plugin > Transactions)

transaction.logs.alert.job=There are no transactions with specified statuses
job.parameter.notset=The parameter {0} is not set.

purchaseunit.item.option.description=Option for {0}

return.to.original.browser=Please return to the original browser to complete your checkout process.
