
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');
import CustomObject = require('dw/object/CustomObject');
import SeekableIterator = require('dw/util/SeekableIterator');
import Map = require('dw/util/Map');

// autogeneratedfile - '/home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/int_flow/meta/custom-objecttype-definitions.xml'

		/**
		Flow Notification

		@scope site
		*/
		interface flowNotification {
			/**
			* 
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/int_flow/meta/custom-objecttype-definitions.xml#7)
			* @isKey true
			*/
			notificationId: string

			/**
			* Flow Order Id
			* @group flow - Flow
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/int_flow/meta/custom-objecttype-definitions.xml#12) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/int_flow/meta/custom-objecttype-definitions.xml#47)
			*/
			flowOrderId: string | null;

			/**
			* SFCC Order Number
			* @group flow - Flow
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/int_flow/meta/custom-objecttype-definitions.xml#20) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/int_flow/meta/custom-objecttype-definitions.xml#48)
			*/
			sfccOrderId: string | null;

			/**
			* Notification
			* @group flow - Flow
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/int_flow/meta/custom-objecttype-definitions.xml#28) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/int_flow/meta/custom-objecttype-definitions.xml#49)
			*/
			notification: string | null;

			/**
			* Data
			* @group flow - Flow
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/int_flow/meta/custom-objecttype-definitions.xml#35) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/int_flow/meta/custom-objecttype-definitions.xml#50)
			*/
			data: string | null;

		}


declare global {
	interface ICustomObjectGetCustomObject {
					/**
		*/
		(type: 'flowNotification', keyValue: string): CustomObject<flowNotification> | null;
		
	}
	interface ICustomObjectQueryCustomObjects {
					/**
		*/
		(type : 'flowNotification', queryAttributes : Map<string, string>, sortstring : string | null) : SeekableIterator<CustomObject<flowNotification>>
		(type : 'flowNotification', querystring : string, sortstring : string | null, ...args : any[]) : SeekableIterator<CustomObject<flowNotification>>
		
	}

	interface ICustomObjectCreateCustomObject {
					/**
		*/
		(type : 'flowNotification', keyValue : string) : CustomObject<flowNotification>
		
	}

	interface ICustomObjectQueryCustomObject {
					/**
		*/
		(type : 'flowNotification', queryAttributes : Map<string, string>, sortstring? : string | null) : CustomObject<flowNotification> | null;
		(type : 'flowNotification', querystring : string, sortstring : string | null, ...args : any[]) : CustomObject<flowNotification> | null;
		
	}
	interface ICustomObjectGetAllCustomObjects {
					/**
		*/
		(type : 'flowNotification') : SeekableIterator<CustomObject<flowNotification>>
		
	}
	interface ICustomObjectTypes {
		flowNotification : CustomObject<flowNotification>;
	}
}