
import FormField = require('dw/web/FormField')
import FormGroup = require('dw/web/FormGroup');
import FormList = require('dw/web/FormList');
import FormAction = require('dw/web/FormAction');
// autogeneratedfile

	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#2)*/
declare class FormProfileCustomer extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#4) */
	firstname : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#15) */
	lastname : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#26) */
	email : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#38) */
	emailconfirm : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#50) */
	phone : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#59) */
	addtoemaillist : FormField<boolean>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#64) */
	getexclusiveoffers : FormField<boolean>
}
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#2)*/
declare class FormProfileLogin extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#71) */
	password : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#83) */
	passwordconfirm : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#94) */
	currentpassword : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#104) */
	newpasswords : FormNewPasswords
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#2)*/
declare class FormProfile extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#3) */
	customer : FormProfileCustomer
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#70) */
	login : FormProfileLogin
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/contactInfo.xml#2)*/
declare class FormContactInfo extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/contactInfo.xml#5) */
	email : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/contactInfo.xml#18) */
	phone : FormField<string>
}
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#2)*/
declare class FormShippingShippingAddress extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#12) */
	addressFields : FormAddress
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#15) */
	shippingMethodID : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#18) */
	shippingAddressUseAsBillingAddress : FormField<boolean>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#20) */
	isGift : FormField<boolean>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#21) */
	giftMessage : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#24) */
	save : FormAction
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#2)*/
declare class FormShipping extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#4) */
	shipmentUUID : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#6) */
	productLineItemUUID : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#9) */
	shippingAddress : FormShippingShippingAddress
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#2)*/
declare class FormBilling extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#4) */
	shippingAddressUseAsBillingAddress : FormField<boolean>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#7) */
	addressFields : FormAddress
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#9) */
	contactInfoFields : FormContactInfo
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#11) */
	paymentMethod : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#13) */
	creditCardFields : FormCreditCard
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#15) */
	subscribe : FormField<boolean>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#18) */
	paypal : FormPaypal
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#21) */
	adyenPaymentFields : FormAdyenPayment
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#24) */
	paypalBillingFields : FormPaypalBillingFields
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#26) */
	bicNumber : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#29) */
	bankListSelection : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#32) */
	klarnaEmail : FormField<string>
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_salesforce_services/cartridges/int_salesforce_services/cartridge/forms/default/coCustomer.xml#2)*/
declare class FormCoCustomer extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_salesforce_services/cartridges/int_salesforce_services/cartridge/forms/default/coCustomer.xml#4) */
	newsletterOptIn : FormNewsletterOptIn
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_salesforce_services/cartridges/int_salesforce_services/cartridge/forms/default/coCustomer.xml#6) */
	email : FormField<string>
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_base/cartridge/forms/default/states.xml#2)*/
declare class FormStates extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_base/cartridge/forms/default/states.xml#3) */
	stateCode : FormField<string>
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_base/cartridge/forms/default/coRegisteredCustomer.xml#2)*/
declare class FormCoRegisteredCustomer extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_base/cartridge/forms/default/coRegisteredCustomer.xml#4) */
	email : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_base/cartridge/forms/default/coRegisteredCustomer.xml#16) */
	password : FormField<string>
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#2)*/
declare class FormAddress extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#4) */
	addressId : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#6) */
	firstName : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#8) */
	lastName : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#10) */
	address1 : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#12) */
	address2 : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#14) */
	city : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#18) */
	postalCode : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#26) */
	country : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#34) */
	states : FormStates
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#37) */
	phone : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#49) */
	apply : FormAction
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#50) */
	remove : FormAction
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#2)*/
declare class FormCreditCard extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#3) */
	paymentMethod : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#5) */
	cardType : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#8) */
	cardNumber : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#12) */
	cardOwner : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#15) */
	expirationMonth : FormField<number>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#35) */
	expirationYear : FormField<number>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#42) */
	securityCode : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#45) */
	saveCard : FormField<boolean>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#47) */
	saveCardAdyen : FormField<boolean>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#50) */
	adyenStateData : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#54) */
	selectedCardID : FormField<string>
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/newPasswords.xml#2)*/
declare class FormNewPasswords extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/newPasswords.xml#3) */
	newpassword : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/newPasswords.xml#14) */
	newpasswordconfirm : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/newPasswords.xml#24) */
	savepaymentmethod : FormField<boolean>
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_base/cartridge/forms/default/paypalBillingFields.xml#2)*/
declare class FormPaypalBillingFields extends FormGroup {

}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/adyenPayment.xml#2)*/
declare class FormAdyenPayment extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/adyenPayment.xml#4) */
	issuer : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/adyenPayment.xml#7) */
	terminalId : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/adyenPayment.xml#8) */
	storeId : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/adyenPayment.xml#11) */
	adyenStateData : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/adyenPayment.xml#12) */
	adyenFingerprint : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/adyenPayment.xml#13) */
	adyenPartialPaymentsOrder : FormField<string>
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_paypal/cartridges/int_paypal/cartridge/forms/default/paypal.xml#2)*/
declare class FormPaypal extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_paypal/cartridges/int_paypal/cartridge/forms/default/paypal.xml#3) */
	paypalOrderID : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_paypal/cartridges/int_paypal/cartridge/forms/default/paypal.xml#4) */
	savePaypalAccount : FormField<boolean>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_paypal/cartridges/int_paypal/cartridge/forms/default/paypal.xml#5) */
	paypalActiveAccount : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_paypal/cartridges/int_paypal/cartridge/forms/default/paypal.xml#6) */
	makeDefaultPaypalAccount : FormField<boolean>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_paypal/cartridges/int_paypal/cartridge/forms/default/paypal.xml#7) */
	billingAgreementID : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_paypal/cartridges/int_paypal/cartridge/forms/default/paypal.xml#8) */
	billingAgreementPayerEmail : FormField<string>
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_salesforce_services/cartridges/int_salesforce_services/cartridge/forms/default/newsletterOptIn.xml#2)*/
declare class FormNewsletterOptIn extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_salesforce_services/cartridges/int_salesforce_services/cartridge/forms/default/newsletterOptIn.xml#4) */
	addtoemaillist : FormField<boolean>
}
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#2)*/
declare class FormGiftCertificatePurchase extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#6) */
	from : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#10) */
	recipient : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#14) */
	recipientEmail : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#23) */
	confirmRecipientEmail : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#32) */
	message : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#37) */
	amount : FormField<number>
}
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#2)*/
declare class FormGiftCertificateBalance extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#47) */
	giftcertificateid : FormField<string>
}
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#2)*/
declare class FormGiftCertificateApply extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#54) */
	giftcertificateid : FormField<string>
}
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#2)*/
declare class FormGiftCertificateRedemption extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#59) */
	amount : FormField<number>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#65) */
	number : FormField<string>
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#2)*/
declare class FormGiftCertificate extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#5) */
	purchase : FormGiftCertificatePurchase
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#46) */
	balance : FormGiftCertificateBalance
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#53) */
	apply : FormGiftCertificateApply
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#58) */
	redemption : FormGiftCertificateRedemption
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#73) */
	redeem : FormAction
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/recaptcha.xml#2)*/
declare class FormRecaptcha extends FormGroup {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/recaptcha.xml#3) */
	recaptchaToken : FormField<string>
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/recaptcha.xml#4) */
	recaptchaAction : FormField<string>
}

declare global {
interface SFCCForms {
	profile: FormProfile
	contactInfo: FormContactInfo
	shipping: FormShipping
	billing: FormBilling
	coCustomer: FormCoCustomer
	states: FormStates
	coRegisteredCustomer: FormCoRegisteredCustomer
	address: FormAddress
	creditCard: FormCreditCard
	newPasswords: FormNewPasswords
	paypalBillingFields: FormPaypalBillingFields
	adyenPayment: FormAdyenPayment
	paypal: FormPaypal
	newsletterOptIn: FormNewsletterOptIn
	giftCertificate: FormGiftCertificate
	recaptcha: FormRecaptcha
}
}


/****** SRFA *******/

interface SfraAction {
    description: string | null;
    label: string | null;
    submitted: boolean | null;
    triggered: boolean | null;
    formType: string;
}

interface SfraFiledOptions {
	checked: boolean,
	htmlValue: string,
	label: string,
	id: string,
	selected: boolean,
	value: string
}

interface SfraFieldBoolean {
	checked: boolean;
	selected: boolean;
}

interface SfraFieldString {
	maxLength: number;
	minLength: number;
	regEx: string
}

interface SfraFieldInteger {
	maxValue: number;
	minValue: number;
}

interface SfraField<T> {
	valid: boolean;
	error: string | null
	readonly attributes: string;
	value: T;
	options: SfraFiledOptions[];
	selectedOption: string;
	formType: string;

	htmlValue: string,
	mandatory: boolean,
	dynamicHtmlName: string
	htmlName: string
}

interface SfraFormBase<T> {
	clear() : void;
	copyFrom(src: object): void;
	toObject(): any;
	valid: boolean;
	base: T
	htmlName: string,
	dynamicHtmlName: string,
	error: string | null,
	attributes: string,
	formType: 'formGroup'
}
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#2)*/
interface SfraFormProfileCustomer {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#4) */
	firstname : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#15) */
	lastname : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#26) */
	email : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#38) */
	emailconfirm : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#50) */
	phone : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#59) */
	addtoemaillist : SfraField<boolean> & SfraFieldBoolean
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#64) */
	getexclusiveoffers : SfraField<boolean> & SfraFieldBoolean
}
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#2)*/
interface SfraFormProfileLogin {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#71) */
	password : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#83) */
	passwordconfirm : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#94) */
	currentpassword : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#104) */
	newpasswords : SfraFormNewPasswords
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#2)*/
interface SfraFormProfile extends SfraFormBase<FormProfile> {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#3) */
	customer : SfraFormProfileCustomer
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/profile.xml#70) */
	login : SfraFormProfileLogin
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/contactInfo.xml#2)*/
interface SfraFormContactInfo extends SfraFormBase<FormContactInfo> {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/contactInfo.xml#5) */
	email : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/contactInfo.xml#18) */
	phone : SfraField<string> & SfraFieldString
}
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#2)*/
interface SfraFormShippingShippingAddress {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#12) */
	addressFields : SfraFormAddress
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#15) */
	shippingMethodID : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#18) */
	shippingAddressUseAsBillingAddress : SfraField<boolean> & SfraFieldBoolean
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#20) */
	isGift : SfraField<boolean> & SfraFieldBoolean
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#21) */
	giftMessage : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#24) */
	save : SfraAction
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#2)*/
interface SfraFormShipping extends SfraFormBase<FormShipping> {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#4) */
	shipmentUUID : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#6) */
	productLineItemUUID : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/storefront-reference-architecture/cartridges/app_storefront_base/cartridge/forms/default/shipping.xml#9) */
	shippingAddress : SfraFormShippingShippingAddress
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#2)*/
interface SfraFormBilling extends SfraFormBase<FormBilling> {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#4) */
	shippingAddressUseAsBillingAddress : SfraField<boolean> & SfraFieldBoolean
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#7) */
	addressFields : SfraFormAddress
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#9) */
	contactInfoFields : SfraFormContactInfo
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#11) */
	paymentMethod : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#13) */
	creditCardFields : SfraFormCreditCard
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#15) */
	subscribe : SfraField<boolean> & SfraFieldBoolean
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#18) */
	paypal : SfraFormPaypal
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#21) */
	adyenPaymentFields : SfraFormAdyenPayment
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#24) */
	paypalBillingFields : SfraFormPaypalBillingFields
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#26) */
	bicNumber : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#29) */
	bankListSelection : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/billing.xml#32) */
	klarnaEmail : SfraField<string> & SfraFieldString
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_salesforce_services/cartridges/int_salesforce_services/cartridge/forms/default/coCustomer.xml#2)*/
interface SfraFormCoCustomer extends SfraFormBase<FormCoCustomer> {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_salesforce_services/cartridges/int_salesforce_services/cartridge/forms/default/coCustomer.xml#4) */
	newsletterOptIn : SfraFormNewsletterOptIn
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_salesforce_services/cartridges/int_salesforce_services/cartridge/forms/default/coCustomer.xml#6) */
	email : SfraField<string> & SfraFieldString
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_base/cartridge/forms/default/states.xml#2)*/
interface SfraFormStates extends SfraFormBase<FormStates> {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_base/cartridge/forms/default/states.xml#3) */
	stateCode : SfraField<string> & SfraFieldString
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_base/cartridge/forms/default/coRegisteredCustomer.xml#2)*/
interface SfraFormCoRegisteredCustomer extends SfraFormBase<FormCoRegisteredCustomer> {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_base/cartridge/forms/default/coRegisteredCustomer.xml#4) */
	email : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_base/cartridge/forms/default/coRegisteredCustomer.xml#16) */
	password : SfraField<string> & SfraFieldString
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#2)*/
interface SfraFormAddress extends SfraFormBase<FormAddress> {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#4) */
	addressId : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#6) */
	firstName : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#8) */
	lastName : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#10) */
	address1 : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#12) */
	address2 : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#14) */
	city : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#18) */
	postalCode : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#26) */
	country : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#34) */
	states : SfraFormStates
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#37) */
	phone : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#49) */
	apply : SfraAction
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/autobahn_client_core/cartridges/autobahn_client_core/cartridge/forms/default/address.xml#50) */
	remove : SfraAction
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#2)*/
interface SfraFormCreditCard extends SfraFormBase<FormCreditCard> {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#3) */
	paymentMethod : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#5) */
	cardType : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#8) */
	cardNumber : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#12) */
	cardOwner : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#15) */
	expirationMonth : SfraField<number> & SfraFieldInteger
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#35) */
	expirationYear : SfraField<number> & SfraFieldInteger
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#42) */
	securityCode : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#45) */
	saveCard : SfraField<boolean> & SfraFieldBoolean
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#47) */
	saveCardAdyen : SfraField<boolean> & SfraFieldBoolean
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#50) */
	adyenStateData : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/creditCard.xml#54) */
	selectedCardID : SfraField<string> & SfraFieldString
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/newPasswords.xml#2)*/
interface SfraFormNewPasswords extends SfraFormBase<FormNewPasswords> {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/newPasswords.xml#3) */
	newpassword : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/newPasswords.xml#14) */
	newpasswordconfirm : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_core/cartridge/forms/default/newPasswords.xml#24) */
	savepaymentmethod : SfraField<boolean> & SfraFieldBoolean
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_integrations_core/cartridges/rvw_integrations_base/cartridge/forms/default/paypalBillingFields.xml#2)*/
interface SfraFormPaypalBillingFields extends SfraFormBase<FormPaypalBillingFields> {

}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/adyenPayment.xml#2)*/
interface SfraFormAdyenPayment extends SfraFormBase<FormAdyenPayment> {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/adyenPayment.xml#4) */
	issuer : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/adyenPayment.xml#7) */
	terminalId : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/adyenPayment.xml#8) */
	storeId : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/adyenPayment.xml#11) */
	adyenStateData : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/adyenPayment.xml#12) */
	adyenFingerprint : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_adyen/cartridges/app_adyen_SFRA/cartridge/forms/default/adyenPayment.xml#13) */
	adyenPartialPaymentsOrder : SfraField<string> & SfraFieldString
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_paypal/cartridges/int_paypal/cartridge/forms/default/paypal.xml#2)*/
interface SfraFormPaypal extends SfraFormBase<FormPaypal> {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_paypal/cartridges/int_paypal/cartridge/forms/default/paypal.xml#3) */
	paypalOrderID : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_paypal/cartridges/int_paypal/cartridge/forms/default/paypal.xml#4) */
	savePaypalAccount : SfraField<boolean> & SfraFieldBoolean
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_paypal/cartridges/int_paypal/cartridge/forms/default/paypal.xml#5) */
	paypalActiveAccount : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_paypal/cartridges/int_paypal/cartridge/forms/default/paypal.xml#6) */
	makeDefaultPaypalAccount : SfraField<boolean> & SfraFieldBoolean
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_paypal/cartridges/int_paypal/cartridge/forms/default/paypal.xml#7) */
	billingAgreementID : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/link_paypal/cartridges/int_paypal/cartridge/forms/default/paypal.xml#8) */
	billingAgreementPayerEmail : SfraField<string> & SfraFieldString
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_salesforce_services/cartridges/int_salesforce_services/cartridge/forms/default/newsletterOptIn.xml#2)*/
interface SfraFormNewsletterOptIn extends SfraFormBase<FormNewsletterOptIn> {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_salesforce_services/cartridges/int_salesforce_services/cartridge/forms/default/newsletterOptIn.xml#4) */
	addtoemaillist : SfraField<boolean> & SfraFieldBoolean
}
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#2)*/
interface SfraFormGiftCertificatePurchase {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#6) */
	from : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#10) */
	recipient : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#14) */
	recipientEmail : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#23) */
	confirmRecipientEmail : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#32) */
	message : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#37) */
	amount : SfraField<number> 
}
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#2)*/
interface SfraFormGiftCertificateBalance {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#47) */
	giftcertificateid : SfraField<string> & SfraFieldString
}
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#2)*/
interface SfraFormGiftCertificateApply {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#54) */
	giftcertificateid : SfraField<string> & SfraFieldString
}
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#2)*/
interface SfraFormGiftCertificateRedemption {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#59) */
	amount : SfraField<number> 
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#65) */
	number : SfraField<string> & SfraFieldString
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#2)*/
interface SfraFormGiftCertificate extends SfraFormBase<FormGiftCertificate> {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#5) */
	purchase : SfraFormGiftCertificatePurchase
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#46) */
	balance : SfraFormGiftCertificateBalance
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#53) */
	apply : SfraFormGiftCertificateApply
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#58) */
	redemption : SfraFormGiftCertificateRedemption
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/giftCertificate.xml#73) */
	redeem : SfraAction
}
/** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/recaptcha.xml#2)*/
interface SfraFormRecaptcha extends SfraFormBase<FormRecaptcha> {
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/recaptcha.xml#3) */
	recaptchaToken : SfraField<string> & SfraFieldString
	 /** @source [definition](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/rvw_autobahn_core/cartridges/rvw_autobahn_core/cartridge/forms/default/recaptcha.xml#4) */
	recaptchaAction : SfraField<string> & SfraFieldString
}

declare global {
interface SFRAServerForms {
	getForm(name: 'profile'): SfraFormProfile
	getForm(name: 'contactInfo'): SfraFormContactInfo
	getForm(name: 'shipping'): SfraFormShipping
	getForm(name: 'billing'): SfraFormBilling
	getForm(name: 'coCustomer'): SfraFormCoCustomer
	getForm(name: 'states'): SfraFormStates
	getForm(name: 'coRegisteredCustomer'): SfraFormCoRegisteredCustomer
	getForm(name: 'address'): SfraFormAddress
	getForm(name: 'creditCard'): SfraFormCreditCard
	getForm(name: 'newPasswords'): SfraFormNewPasswords
	getForm(name: 'paypalBillingFields'): SfraFormPaypalBillingFields
	getForm(name: 'adyenPayment'): SfraFormAdyenPayment
	getForm(name: 'paypal'): SfraFormPaypal
	getForm(name: 'newsletterOptIn'): SfraFormNewsletterOptIn
	getForm(name: 'giftCertificate'): SfraFormGiftCertificate
	getForm(name: 'recaptcha'): SfraFormRecaptcha
}
}

declare global {
interface SRFAForms {
	profile: SfraFormProfile
	contactInfo: SfraFormContactInfo
	shipping: SfraFormShipping
	billing: SfraFormBilling
	coCustomer: SfraFormCoCustomer
	states: SfraFormStates
	coRegisteredCustomer: SfraFormCoRegisteredCustomer
	address: SfraFormAddress
	creditCard: SfraFormCreditCard
	newPasswords: SfraFormNewPasswords
	paypalBillingFields: SfraFormPaypalBillingFields
	adyenPayment: SfraFormAdyenPayment
	paypal: SfraFormPaypal
	newsletterOptIn: SfraFormNewsletterOptIn
	giftCertificate: SfraFormGiftCertificate
	recaptcha: SfraFormRecaptcha
}
}