
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - '/home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface Category {
			/**
			* FAQ
			* @group WGACACustomAttributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#5) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#106)
			*/
			faqOnPlp: MarkupText | null;

			/**
			* H1 Content Tracker
			* @group WGACACustomAttributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#12) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#104)
			*/
			h1ContentTracker: MarkupText | null;

			/**
			* H2 Content Tracker
			* @group WGACACustomAttributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#19) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#105)
			*/
			h2ContentTracker: MarkupText | null;

			/**
			* Navigation Text Color

				Enter a hex color value to change the text color of this category in the navigation.
			* @group WGACACustomAttributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#26) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#101)
			*/
			navigationTextColor: string | null;

			/**
			* Popular Search Keywords

				Popular Search Keywords
			* @group WGACACustomAttributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#35) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#103)
			*/
			popularSearchKeywords: string | null;

			/**
			* Shop Now Text

				This represent shop now text for main category.
			* @group WGACACustomAttributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#43) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#102)
			*/
			shopnowtext: string | null;

			/**
			* Size Chart

				Used to define the content asset ID of the Size Chart that is appropriate for products whose PRIMARY category is the associated category (and its children). Whenever a product detail page (or quick view) is rendered, the Size Chart link is populated based on the value of this attribute for the products primary categorization. If not defined, NO size chart link is displayed.
			* 
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#52) 
			*/
			sizeChartID: string | null;

			/**
			* Category Landing Slot Image

				Image used on either the top or bottom slot on the category landing pages.
			* 
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#61) 
			*/
			slotBannerImage: MediaFile | null;

			/**
			* Hero Banner

				Hero Banner image for PLP
			* @group WGACACustomAttributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#69) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#107)
			*/
			heroBanner: MediaFile | null;

			/**
			* Hero Banner Mobile

				Hero Banner image for PLP - mobile view
			* @group WGACACustomAttributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#77) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#108)
			*/
			heroBannerMobile: MediaFile | null;

			/**
			* Live Selling Category

				Marks this category as a live selling PLP category.
			* @group WGACACustomAttributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#85) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#109)
			*/
			isLiveSellingCategory: boolean | null;

		}
		interface CustomerAddress {
			/**
			* is Tiktok Order
			* @group Standard - Standard Address
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#160) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#187)
			*/
			isTiktokOrder: boolean | null;

		}
		interface Order {
			/**
			* RTW Order
			* @group RTWOrder - RTW Order
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#205) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#263)
			*/
			isRTWOrder: boolean | null;

			/**
			* Is Bambuser Order
			* @group RTWOrder - RTW Order
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#211) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#264)
			*/
			isbambuserorder: boolean | null;

			/**
			* order Source
			* 
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#217) 
			*/
			orderSource: string | null;

			/**
			* Is Live Selling Order
			* @group RTWOrder - RTW Order
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#224) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#265)
			*/
			isLiveSellingOrder: boolean | null;

			/**
			* Is CSC Handoff Order

				True when the order contains at least one line item added by Customer Service / BM handoff. Independent of isLiveSellingOrder - a CSC handoff order is only also a live selling order when the agent explicitly marks a line item as live selling.
			* @group RTWOrder - RTW Order
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#230) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#266)
			*/
			isCSCHandoffOrder: boolean | null;

			/**
			* Live Selling Host Name
			* @group RTWOrder - RTW Order
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#237) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#267)
			*/
			liveSellingHostName: string | null;

			/**
			* Live Selling Event Date
			* @group RTWOrder - RTW Order
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#244) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#268)
			*/
			liveSellingEventDate: string | null;

			/**
			* CSC Order Notes

				Note entered by the CSC agent at handoff time. Written to a real Business Manager order note and included in the fulfillment payload when the order is placed.
			* @group RTWOrder - RTW Order
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#251) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#269)
			*/
			cscOrderNotes: string | null;

		}
		interface Shipment {
			/**
			* CSC Order Notes

				Temporary basket storage for the order note entered by a CSC agent.
			* @group CSCOrderNotes - CSC Order Notes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#276) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#288)
			*/
			cscOrderNotes: string | null;

		}
		interface OrderAddress {
			/**
			* Is Tiktok Order

				used for mapping the order of Tiktok
			* @group Standard - Standard Address
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#295) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#323)
			*/
			isTiktokOrder: boolean | null;

		}
		interface Product {
			/**
			* Related Product

				Related Product SKU for redirecting
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#331) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1491)
			*/
			relatedProduct: string | null;

			/**
			* About the Bag

				WGACA About the Bag
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#344) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1492)
			*/
			about_the_bag: string | null;

			/**
			* Amazon Earring Design
			* @group AmazonProductFeed - Amazon Product Feed
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#357) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1598)
			*/
			amazonEarring_Design: EnumValue<'ball' | 'climber' | 'cluster' | 'cuff' | 'dangle' | 'drop' | 'fake_gauge' | 'fake_plug' | 'front_and_back' | 'hoop' | 'jacket' | 'non_pierced' | 'stud' | 'threader' | 'wrap' | null> | null;

			/**
			* Export Product To Amazon

				Export Product To Amazon
			* @group AmazonProductFeed - Amazon Product Feed
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#430) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1596)
			*/
			amazonProductExport: boolean | null;

			/**
			* Amazon Product Type
			* @group AmazonProductFeed - Amazon Product Feed
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#441) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1599)
			*/
			amazonProduct_Type: string | null;

			/**
			* Export Product To Amazon Today

				Export Product To Amazon Today
			* @group AmazonProductFeed - Amazon Product Feed
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#453) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1597)
			*/
			amazonTodayProductExport: boolean | null;

			/**
			* Authenticity Card

				WGACA Authenticity Card
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#464) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1493)
			*/
			authenticity_card: boolean | null;

			/**
			* Badge Background Colors

				Set the color to be used for the badge background. Use css appropriate values.
			* @group badges - Badges
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#475) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1575)
			*/
			badgeBackgroundColors: ReadonlyArray<string> | null;

			/**
			* Badge Border Colors

				Set the color to be used for the badge border. Use css appropriate values.
			* @group badges - Badges
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#487) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1576)
			*/
			badgeBorderColors: ReadonlyArray<string> | null;

			/**
			* Badge Font Sizes

				Set the font size to be used for the badge text. Use css appropriate values.
			* @group badges - Badges
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#499) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1573)
			*/
			badgeFontSizes: ReadonlyArray<string> | null;

			/**
			* Badge Text Colors

				Set the color to be used for the badge text. Use css appropriate values.
			* @group badges - Badges
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#511) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1574)
			*/
			badgeTextColors: ReadonlyArray<string> | null;

			/**
			* Bag Silhouette
			* @group TikTok - TikTok
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#523) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1604)
			*/
			bagSilhouette: string | null;

			/**
			* Closure

				WGACA Closure
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#535) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1494)
			*/
			closure: string | null;

			/**
			* Condition Name

				WGACA Condition Name
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#548) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1496)
			*/
			condition_name: string | null;

			/**
			* Condition Notes

				WGACA Condition Notes
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#561) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1497)
			*/
			condition_notes: string | null;

			/**
			* Country of Origin

				WGACA Country of Origin
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#574) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1498)
			*/
			country_of_origin: string | null;

			/**
			* Depth

				WGACA Depth
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#587) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1499)
			*/
			depth: string | null;

			/**
			* Depth
			* 
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#600) 
			*/
			dimDepth: string | null;

			/**
			* Height
			* 
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#612) 
			*/
			dimHeight: string | null;

			/**
			* Weight
			* 
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#624) 
			*/
			dimWeight: string | null;

			/**
			* Width
			* 
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#636) 
			*/
			dimWidth: string | null;

			/**
			* Enable RTW Product
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#648) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1537)
			*/
			enableRTWProduct: boolean | null;

			/**
			* Live Selling Product

				Marks this product as a live selling item. Price and storefront Add to Cart are hidden on PLP and PDP.
			* @group LiveSelling - Live Selling
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#658) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1545)
			*/
			isLiveSellingProduct: boolean | null;

			/**
			* Live Selling Item ID

				Item ID shown on the live selling PLP and PDP.
			* @group LiveSelling - Live Selling
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#670) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1546)
			*/
			liveSellingItemID: string | null;

			/**
			* Cartons
			* @group FedEx Attributes - FedEx Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#683) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1583)
			*/
			fdxCartons: ReadonlyArray<string> | null;

			/**
			* Components or materials used in the product

				Example: Cotton
			* @group FedEx Attributes - FedEx Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#694) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1580)
			*/
			fdxComposition: string | null;

			/**
			* Country of Origin

				Country of Origin (CoO) of the product. Two-letter ISO code of the product Country of Origin.
			* @group FedEx Attributes - FedEx Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#707) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1581)
			*/
			fdxCountryOfOrigin: string | null;

			/**
			* Export Control Classification Number
			* @group FedEx Attributes - FedEx Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#720) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1585)
			*/
			fdxEccn: string | null;

			/**
			* Gender

				Defines whether or not the product, typically with textiles, is a men, women, boy, girl, or unisex. Example: Women's blouse
			* @group FedEx Attributes - FedEx Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#732) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1591)
			*/
			fdxGender: string | null;

			/**
			* Hazardous Flag

				Defines whether a product is hazardous or not:
			* @group FedEx Attributes - FedEx Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#745) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1582)
			*/
			fdxHazFlag: boolean | null;

			/**
			* Hs Code

				Code that allows the calculation of tax payable in the destination country or territory of the shipment.
			* @group FedEx Attributes - FedEx Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#756) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1584)
			*/
			fdxHsCode: string | null;

			/**
			* List of countries to which the product cannot enter

				Example: importFlag = "AR,PE,BO,BR". Twoletter ISO code of the product country or territory.
			* @group FedEx Attributes - FedEx Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#769) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1588)
			*/
			fdxImportFlag: string | null;

			/**
			* Is fixed pricing allowed for current product
			* @group FedEx Attributes - FedEx Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#782) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1592)
			*/
			fdxIsFixedPricing: boolean | null;

			/**
			* List of countries that require a license for the product.

				Example: licenseFlag = "AR,PE,BO,BR". Twoletter ISO code of the product country or territory.
			* @group FedEx Attributes - FedEx Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#792) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1589)
			*/
			fdxLicenseFlag: string | null;

			/**
			* Multi Country of Origin
			* @group FedEx Attributes - FedEx Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#805) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1587)
			*/
			fdxMultiCountryOfOrigin: boolean | null;

			/**
			* Unit Dimentions

				This field defines the unit of measurement used to express the product dimensions. Possible values are: inches (in), centimeters (cm)
			* @group FedEx Attributes - FedEx Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#815) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1590)
			*/
			fdxUnitDimension: EnumValue<'in' | 'cm' | null> | null;

			/**
			* Unit Weight
			* @group FedEx Attributes - FedEx Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#837) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1586)
			*/
			fdxUnitWeight: EnumValue<'lb' | 'kg' | 'oz' | 'g' | null> | null;

			/**
			* Final Sale

				WGACA Final Sale
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#866) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1500)
			*/
			final_sale: boolean | null;

			/**
			* Genre
			* 
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#877) 
			*/
			gameGenre: ReadonlyArray<EnumValue<'Action' | 'Educational' | 'Kids' | 'Racing' | 'Role-Playing' | 'Sports' | 'Strategy'>> | null;

			/**
			* Handle

				WGACA Handle
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#919) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1501)
			*/
			handle: string | null;

			/**
			* Handle Drop
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#932) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1502)
			*/
			handle_drop: string | null;

			/**
			* Hardware

				WGACA Hardware
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#944) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1503)
			*/
			hardware: string | null;

			/**
			* Height

				WGACA Height
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#957) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1504)
			*/
			height: string | null;

			/**
			* Image Aspect Ratio
			* 
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#970) 
			*/
			imageAspectRatio: string | null;

			/**
			* Image path LOA
			* @group TikTok - TikTok
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#982) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1605)
			*/
			imagepathLOA: string | null;

			/**
			* Includes
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#994) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1505)
			*/
			includes: string | null;

			/**
			* Interior

				WGACA Interior
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1006) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1506)
			*/
			interior: string | null;

			/**
			* Interior Pockets
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1019) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1507)
			*/
			interior_pockets: string | null;

			/**
			* Is Tiktok Enabled
			* @group TikTok - TikTok
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1031) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1603)
			*/
			isTiktokEnabled: boolean | null;

			/**
			* length

				WGACA length
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1041) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1508)
			*/
			length: string | null;

			/**
			* Lining

				WGACA Lining
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1054) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1509)
			*/
			lining: string | null;

			/**
			* Location
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1067) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1535)
			*/
			location: ReadonlyArray<EnumValue<'Online Only' | 'Beverly Hills' | 'Soho' | 'Wooster'>> | null;

			/**
			* Make Offer Enabled

				WGACA Make Offer Enabled
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1097) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1510)
			*/
			make_offer_enabled: boolean | null;

			/**
			* Material

				WGACA Material
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1108) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1511)
			*/
			material: string | null;

			/**
			* Page URL PIM Slug

				WGACA Page URL PIM Slug
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1121) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1512)
			*/
			page_url: string | null;

			/**
			* PLP Custom Refinement Category

				Parent and child category separated by a " - " i.e. "Bags - Backpacks". This is used for custom filtering on certain PLP's.
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1134) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1513)
			*/
			plp_category_refinement: string | null;

			/**
			* PLP Custom Refinement Category  (Multi)
			* 
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1147) 
			*/
			plp_category_refinement_multi: ReadonlyArray<string> | null;

			/**
			* Refinement Color
			* 
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1158) 
			*/
			refinementColor: EnumValue<'beige' | 'black' | 'blue' | 'bronze' | 'brown' | 'burgundy' | 'clear' | 'colorless' | 'cream' | 'gold' | 'green' | 'grey' | 'gunmetal' | 'leather' | 'miscellaneous' | 'natural' | 'navy' | 'orange' | 'palladium' | 'pink' | 'purple' | 'red' | 'silver' | 'tan' | 'white' | 'yellow' | null> | null;

			/**
			* Resolution
			* 
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1275) 
			*/
			resolution: string | null;

			/**
			* Season

				WGACA Season
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1287) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1514)
			*/
			season: string | null;

			/**
			* Serial

				WGACA Serial
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1300) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1515)
			*/
			serial: string | null;

			/**
			* Shipping Restrictions

				WGACA Shipping Restrictions
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1313) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1516)
			*/
			shipping_restrictions: boolean | null;

			/**
			* Shipping Returns

				WGACA Shipping Returns
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1324) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1517)
			*/
			shipping_returns: string | null;

			/**
			* Sizing

				WGACA Sizing
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1337) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1519)
			*/
			sizing: string | null;

			/**
			* Skip Sync

				WGACA Skip Sync
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1350) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1521)
			*/
			skip_sync: boolean | null;

			/**
			* Slug

				WGACA Slug
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1361) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1523)
			*/
			slug: string | null;

			/**
			* Strap Drop 1

				WGACA Strap Drop 1
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1374) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1524)
			*/
			strap_drop_1: string | null;

			/**
			* Strap Drop 2

				WGACA Strap Drop 2
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1387) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1525)
			*/
			strap_drop_2: string | null;

			/**
			* Product Notes
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1400) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1526)
			*/
			uid: string | null;

			/**
			* URL Key

				WGACA URL Key
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1411) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1527)
			*/
			url_key: string | null;

			/**
			* Weight

				WGACA Weight
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1424) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1528)
			*/
			weight: string | null;

			/**
			* Width

				WGACA Width
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1437) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1529)
			*/
			width: string | null;

			/**
			* Year

				WGACA Year
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1450) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1530)
			*/
			year: string | null;

			/**
			* Product Category
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1463) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1540)
			*/
			pCategory: string | null;

			/**
			* Product Sub Category
			* @group WGACA-Custom-Attributes - WGACA Custom Attributes
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1475) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1541)
			*/
			pSubCategory: string | null;

		}
		interface Promotion {
			/**
			* Enable Special Promotion Callout Msg

				Enable Special Promotion Callout Msg to display when discount is 0
			* @group enableSpecialPromotionCalloutMsg - Enable Special Promotion Callout Msg
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1689) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1700)
			*/
			enableSpecialPromotionCalloutMsg: boolean | null;

		}
		interface SitePreferences {
			/**
			* Custom Header scripts

				it will include JS in head tag for all pages.
			* @group WGACA Configs - WGACA Custom Configurations
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1707) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1917)
			*/
			CustomHeaderScripts: string | null;

			/**
			* Blog Categories in JSON format

				Enter the category structure here for categorizing blog articles.
			* 
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1714) 
			*/
			blogCategories: string | null;

			/**
			* Disable Account Registration Email Send

				Disable Account Registration Email Send
			* @group WGACA Configs - WGACA Custom Configurations
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1721) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1915)
			*/
			disableAccountRegistrationEmailSend: boolean | null;

			/**
			* Disable Make An Offer

				Disable Make An Offer
			* @group WGACA Configs - WGACA Custom Configurations
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1729) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1911)
			*/
			disableMakeAnOfferDisplay: boolean | null;

			/**
			* Disable Order Confirmation

				Disable Order Confirmation
			* @group WGACA Configs - WGACA Custom Configurations
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1737) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1912)
			*/
			disableOrderConfirmation: boolean | null;

			/**
			* Disable Request Next

				Disable Request Next
			* 
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1745) 
			*/
			disableRequestNextDisplay: boolean | null;

			/**
			* Enable Frenzy Recommendation on Home page

				Enable Frenzy Recommendation on Home page
			* @group Frenzy recommendation - Frenzy recommendation
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1752) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1935)
			*/
			enableFrenzyRecommendationOnHome: boolean | null;

			/**
			* Enable Frenzy Recommendation on PDP page

				Enable Frenzy Recommendation on PDP page
			* @group Frenzy recommendation - Frenzy recommendation
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1759) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1936)
			*/
			enableFrenzyRecommendationOnPDP: boolean | null;

			/**
			* Enable Frenzy Recommendation On Search

				Enable Frenzy Recommendation On Search
			* @group Frenzy recommendation - Frenzy recommendation
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1766) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1937)
			*/
			enableFrenzyRecommendationOnSearch: boolean | null;

			/**
			* Enable Frenzy Recommendation On Search Bar

				Enable Frenzy Recommendation On Search Bar
			* @group Frenzy recommendation - Frenzy recommendation
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1773) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1938)
			*/
			enableFrenzyRecommendationOnSearchBar: boolean | null;

			/**
			* Enable Tangiblee
			* @group WGACA Configs - WGACA Custom Configurations
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1780) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1916)
			*/
			enableTangiblee: boolean | null;

			/**
			* North Beam Enabled
			* @group northBeamConfig - North Beam Config
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1787) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1922)
			*/
			isNorthBeamEnabled: boolean | null;

			/**
			* Smart API Key
			* @group smartyAddressAutocomplete - Smarty Address Autocomplete
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1793) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1944)
			*/
			smartyAPIKey: string | null;

			/**
			* Smarty API URL

				Smarty API URL
			* @group smartyAddressAutocomplete - Smarty Address Autocomplete
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1800) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1943)
			*/
			smartyAPIUrl: string | null;

			/**
			* Smarty Address URL
			* @group smartyAddressAutocomplete - Smarty Address Autocomplete
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1808) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1945)
			*/
			smartyAddressURL: string | null;

			/**
			* Smarty address enabled

				Smarty address enabled
			* @group smartyAddressAutocomplete - Smarty Address Autocomplete
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1815) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1942)
			*/
			smartyEnabled: boolean | null;

			/**
			* Storefront Base URL
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1822) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1907)
			*/
			storefrontBaseUrl: string | null;

			/**
			* OneTrust Consent Script
			* @group OneTrust Configs - OneTrust Cookie Configurations
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1829) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1950)
			*/
			OneTrustConsentScript: string | null;

			/**
			* Enable OneTrust
			* @group OneTrust Configs - OneTrust Cookie Configurations
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1835) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1949)
			*/
			OneTrustEnable: boolean | null;

			/**
			* List Of Non-Authorized Brands
			* @group WGACA Configs - WGACA Custom Configurations
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1842) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1918)
			*/
			NonAuthorizedBrands: string | null;

			/**
			* Live Selling Event ID

				Static identifier for the current live selling event, shared across all live selling products.
			* @group LiveSelling - Live Selling
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1849) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1926)
			*/
			liveSellingEventID: string | null;

			/**
			* Live Selling Host Name

				Static host name for the current live selling event, shared across all live selling products.
			* @group LiveSelling - Live Selling
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1857) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1927)
			*/
			liveSellingHostName: string | null;

			/**
			* Live Selling Event Date

				Static event date for the current live selling event, shared across all live selling products.
			* @group LiveSelling - Live Selling
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1865) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1928)
			*/
			liveSellingEventDate: string | null;

			/**
			* Live Selling Badge Text

				Static badge text shown on live selling PLP/PDP products. Defaults to LIVE if left blank.
			* @group LiveSelling - Live Selling
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1873) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1929)
			*/
			liveSellingBadgeText: string | null;

			/**
			* CSC Handoff Expiration (Hours)

				Number of hours a CSC/live selling line item may sit unpurchased in a customer's basket before it is automatically removed. Defaults to 5 minutes (as a fraction of an hour) if left blank.
			* @group LiveSelling - Live Selling
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1881) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1930)
			*/
			cscHandoffExpirationHours: number | null;

			/**
			* Live Selling Platform

				Placeholder attribute, not yet wired into any code - platform the live selling event is/will be hosted on (e.g. Instagram, TikTok, Bambuser). Created for future use.
			* @group LiveSelling - Live Selling
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1888) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1931)
			*/
			liveSellingPlatform: string | null;

		}
		interface Store {
			/**
			* 
			* 
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1957) 
			*/
			storeType: EnumValue<'retail' | 'outlet' | 'comingSoon' | 'other' | null> | null;

		}
	}
}

declare global {
	interface IGetCustomPreferenceValue {
					/**
			* Custom Header scripts

				it will include JS in head tag for all pages.
			* @group WGACA Configs - WGACA Custom Configurations
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1707) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1917)
			*/
			(name: 'CustomHeaderScripts'): string | null;
			
			/**
			* Blog Categories in JSON format

				Enter the category structure here for categorizing blog articles.
			* 
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1714) 
			*/
			(name: 'blogCategories'): string | null;
			
			/**
			* Disable Account Registration Email Send

				Disable Account Registration Email Send
			* @group WGACA Configs - WGACA Custom Configurations
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1721) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1915)
			*/
			(name: 'disableAccountRegistrationEmailSend'): boolean | null;
			
			/**
			* Disable Make An Offer

				Disable Make An Offer
			* @group WGACA Configs - WGACA Custom Configurations
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1729) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1911)
			*/
			(name: 'disableMakeAnOfferDisplay'): boolean | null;
			
			/**
			* Disable Order Confirmation

				Disable Order Confirmation
			* @group WGACA Configs - WGACA Custom Configurations
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1737) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1912)
			*/
			(name: 'disableOrderConfirmation'): boolean | null;
			
			/**
			* Disable Request Next

				Disable Request Next
			* 
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1745) 
			*/
			(name: 'disableRequestNextDisplay'): boolean | null;
			
			/**
			* Enable Frenzy Recommendation on Home page

				Enable Frenzy Recommendation on Home page
			* @group Frenzy recommendation - Frenzy recommendation
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1752) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1935)
			*/
			(name: 'enableFrenzyRecommendationOnHome'): boolean | null;
			
			/**
			* Enable Frenzy Recommendation on PDP page

				Enable Frenzy Recommendation on PDP page
			* @group Frenzy recommendation - Frenzy recommendation
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1759) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1936)
			*/
			(name: 'enableFrenzyRecommendationOnPDP'): boolean | null;
			
			/**
			* Enable Frenzy Recommendation On Search

				Enable Frenzy Recommendation On Search
			* @group Frenzy recommendation - Frenzy recommendation
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1766) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1937)
			*/
			(name: 'enableFrenzyRecommendationOnSearch'): boolean | null;
			
			/**
			* Enable Frenzy Recommendation On Search Bar

				Enable Frenzy Recommendation On Search Bar
			* @group Frenzy recommendation - Frenzy recommendation
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1773) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1938)
			*/
			(name: 'enableFrenzyRecommendationOnSearchBar'): boolean | null;
			
			/**
			* Enable Tangiblee
			* @group WGACA Configs - WGACA Custom Configurations
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1780) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1916)
			*/
			(name: 'enableTangiblee'): boolean | null;
			
			/**
			* North Beam Enabled
			* @group northBeamConfig - North Beam Config
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1787) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1922)
			*/
			(name: 'isNorthBeamEnabled'): boolean | null;
			
			/**
			* Smart API Key
			* @group smartyAddressAutocomplete - Smarty Address Autocomplete
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1793) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1944)
			*/
			(name: 'smartyAPIKey'): string | null;
			
			/**
			* Smarty API URL

				Smarty API URL
			* @group smartyAddressAutocomplete - Smarty Address Autocomplete
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1800) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1943)
			*/
			(name: 'smartyAPIUrl'): string | null;
			
			/**
			* Smarty Address URL
			* @group smartyAddressAutocomplete - Smarty Address Autocomplete
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1808) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1945)
			*/
			(name: 'smartyAddressURL'): string | null;
			
			/**
			* Smarty address enabled

				Smarty address enabled
			* @group smartyAddressAutocomplete - Smarty Address Autocomplete
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1815) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1942)
			*/
			(name: 'smartyEnabled'): boolean | null;
			
			/**
			* Storefront Base URL
			* @group Storefront Configs - Storefront Configurations
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1822) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1907)
			*/
			(name: 'storefrontBaseUrl'): string | null;
			
			/**
			* OneTrust Consent Script
			* @group OneTrust Configs - OneTrust Cookie Configurations
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1829) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1950)
			*/
			(name: 'OneTrustConsentScript'): string | null;
			
			/**
			* Enable OneTrust
			* @group OneTrust Configs - OneTrust Cookie Configurations
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1835) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1949)
			*/
			(name: 'OneTrustEnable'): boolean | null;
			
			/**
			* List Of Non-Authorized Brands
			* @group WGACA Configs - WGACA Custom Configurations
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1842) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1918)
			*/
			(name: 'NonAuthorizedBrands'): string | null;
			
			/**
			* Live Selling Event ID

				Static identifier for the current live selling event, shared across all live selling products.
			* @group LiveSelling - Live Selling
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1849) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1926)
			*/
			(name: 'liveSellingEventID'): string | null;
			
			/**
			* Live Selling Host Name

				Static host name for the current live selling event, shared across all live selling products.
			* @group LiveSelling - Live Selling
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1857) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1927)
			*/
			(name: 'liveSellingHostName'): string | null;
			
			/**
			* Live Selling Event Date

				Static event date for the current live selling event, shared across all live selling products.
			* @group LiveSelling - Live Selling
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1865) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1928)
			*/
			(name: 'liveSellingEventDate'): string | null;
			
			/**
			* Live Selling Badge Text

				Static badge text shown on live selling PLP/PDP products. Defaults to LIVE if left blank.
			* @group LiveSelling - Live Selling
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1873) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1929)
			*/
			(name: 'liveSellingBadgeText'): string | null;
			
			/**
			* CSC Handoff Expiration (Hours)

				Number of hours a CSC/live selling line item may sit unpurchased in a customer's basket before it is automatically removed. Defaults to 5 minutes (as a fraction of an hour) if left blank.
			* @group LiveSelling - Live Selling
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1881) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1930)
			*/
			(name: 'cscHandoffExpirationHours'): number | null;
			
			/**
			* Live Selling Platform

				Placeholder attribute, not yet wired into any code - platform the live selling event is/will be hosted on (e.g. Instagram, TikTok, Bambuser). Created for future use.
			* @group LiveSelling - Live Selling
			* @source [attribute](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1888) | [group](file:///home/inno-rakesh/Desktop/err/work/sf/autobahn/data/clientmeta/autobahn_client_core/meta/system-objecttype-extensions.xml#1931)
			*/
			(name: 'liveSellingPlatform'): string | null;
			
	}
}