## cartridge.properties for cartridge bambuser_sfra_changes
#Tue Oct 29 13:42:37 CEST 2022
demandware.cartridges.bambuser_sfra_changes.multipleLanguageStorefront=true
demandware.cartridges.bambuser_sfra_changes.id=bambuser_sfra_changes
