##
# Account controller properties
##
account.show.title=Autobahn - Account-Show
account.show.description=Account-Show controller of the Autobahn website
account.show.keywords=Autobahn,Account,Show
account.editprofile.title=Autobahn - Account-EditProfile
account.editprofile.description=Account-EditProfile controller of the Autobahn website
account.editprofile.keywords=Autobahn,Account,EditProfile
account.editpassword.title=Autobahn - Account-EditPassword
account.editpassword.description=Account-EditPassword controller of the Autobahn website
account.editpassword.keywords=Autobahn,Account,EditPassword
account.passwordreset.title=Autobahn - Account-PasswordReset
account.passwordreset.description=Account-PasswordReset controller of the Autobahn website
account.passwordreset.keywords=Autobahn,Account,PasswordReset
account.setnewpassword.title=Autobahn - Account-SetNewPassword
account.setnewpassword.description=Account-SetNewPassword controller of the Autobahn website
account.setnewpassword.keywords=Autobahn,Account,SetNewPassword

##
# Address controller properties
##
address.addaddress.title=Autobahn - Address-AddAddress
address.addaddress.description=Address-AddAddress controller of the Autobahn website
address.addaddress.keywords=Autobahn,Address,AddAddress
address.editaddress.title=Autobahn - Address-EditAddress
address.editaddress.description=Address-EditAddress controller of the Autobahn website
address.editaddress.keywords=Autobahn,Address,EditAddress

##
# Cart properties
##
cart.show.title=Autobahn - Cart
cart.show.description=Cart of the Autobahn website
cart.show.keywords=Autobahn,Cart

##
# Checkout properties
# Checkout stages:
# - login
# - shipping
# - payment
# - placeOrder
# - submitted
##
checkout.default.title=Autobahn - Checkout
checkout.default.description=Checkout of the Autobahn website
checkout.default.keywords=Autobahn,Checkout
checkout.login.title=Autobahn - Checkout - Login
checkout.login.description=Checkout - Please login before moving forward
checkout.login.keywords=Autobahn,Checkout,Login
checkout.shipping.title=Autobahn - Checkout - Shipping details
checkout.shipping.description=Checkout - Enter your shipping address details and shipping method
checkout.shipping.keywords=Autobahn,Checkout,Shipping
checkout.payment.title=Autobahn - Checkout - Payment details
checkout.payment.description=Checkout - Enter your billing address details and payment method
checkout.payment.keywords=Autobahn,Checkout,Payment
checkout.placeOrder.title=Autobahn - Checkout - Review Order
checkout.placeOrder.description=Checkout - Review your order
checkout.placeOrder.keywords=Autobahn,Checkout,Review
checkout.submitted.title=Autobahn - Checkout
checkout.submitted.description=Checkout of the Autobahn website
checkout.submitted.keywords=Autobahn,Checkout

##
# ContactUs controller properties
##
contactus.landing.title=Autobahn - ContactUs-Landing
contactus.landing.description=ContactUs-Landing controller of the Autobahn website
contactus.landing.keywords=Autobahn,ContactUs,Landing

##
# Default controller properties
##
default.start.title=Autobahn - Default-Start
default.start.description=Default-Start controller of the Autobahn website
default.start.keywords=Autobahn,Default,Start

##
# Error controller properties
##
error.start.title=Autobahn - Error-Start
error.start.description=Error-Start controller of the Autobahn website
error.start.keywords=Autobahn,Error,Start
error.errorcode.title=Autobahn - Error-ErrorCode
error.errorcode.description=Error-ErrorCode controller of the Autobahn website
error.errorcode.keywords=Autobahn,Error,ErrorCode

##
# Login controller properties
##
login.show.title=Autobahn - Login-Show
login.show.description=Login-Show controller of the Autobahn website
login.show.keywords=Autobahn,Login,Show
login.oauthlogin.title=Autobahn - Login-OAuthLogin
login.oauthlogin.description=Login-OAuthLogin controller of the Autobahn website
login.oauthlogin.keywords=Autobahn,Login,OAuthLogin
login.oauthreentry.title=Autobahn - Login-OAuthReentry
login.oauthreentry.description=Login-OAuthReentry controller of the Autobahn website
login.oauthreentry.keywords=Autobahn,Login,OAuthReentry

##
# Order controller properties
##
order.confirm.title=Autobahn - Order Confirmation
order.confirm.description=Order confirmation of the Autobahn website
order.confirm.keywords=Autobahn,Order,Confirmation,Thanks
order.track.title=Autobahn - Order Track
order.track.description=Order Track of the Autobahn website
order.track.keywords=Autobahn,Order,Track,Thanks
order.history.title=Autobahn - Order History
order.history.description=Order history of the Autobahn website
order.history.keywords=Autobahn,Order,History,Thanks
order.details.title=Autobahn - Order Details
order.details.description=Order details of the Autobahn website
order.details.keywords=Autobahn,Order,Details,Thanks
order.filtered.title=Autobahn - Order Filtered
order.filtered.description=Order filtered of the Autobahn website
order.filtered.keywords=Autobahn,Order,Filtered,Thanks

##
# PaymentInstruments controller properties
##
paymentinstruments.list.title=Autobahn - PaymentInstruments List
paymentinstruments.list.description=PaymentInstruments List of the Autobahn website
paymentinstruments.list.keywords=Autobahn,PaymentInstruments,List,Thanks
paymentinstruments.addpayment.title=Autobahn - PaymentInstruments AddPayment
paymentinstruments.addpayment.description=PaymentInstruments AddPayment of the Autobahn website
paymentinstruments.addpayment.keywords=Autobahn,PaymentInstruments,AddPayment,Thanks

##
# Stores controller properties
##
stores.find.title=Autobahn - Stores Find
stores.find.description=Stores Find of the Autobahn website
stores.find.keywords=Autobahn,Stores,Find,Thanks
