## cartridge.properties for cartridge rvw_integrations_base
#Tue Dec 17 2019 09:10:00 GMT-0600 (CST)
demandware.cartridges.rvw_integrations_base.multipleLanguageStorefront=true
demandware.cartridges.rvw_integrations_base.id=rvw_integrations_base
