text.remove.cart.item=Remove
label.sales.tax= Estimated Sales Tax
label.shipping.cost= Estimated Shipping cost
text.log.in=log in
text.quick.checkout=for a quick checkout
label.cart.total=cart total
label.shipping.details.checkout=Shipping details and sales tax will be calculated during checkout
button.gotocart=go to cart
info.cart.empty.msg=There are no items in cart.
link.view.wishlist=view your wishlist
text.product.img=Product Image
error.removed.online.catalog=This product was recently removed from our online catalog. Please remove this item to proceed with checkout.
placholder.text.promo.code.input= Enter promo code
label.promo.code=Promo Code
button.submit.promo.code=Apply
success.promo.code.applied=Promo code applied successfully
error.promo.code.applied=Promo code is not valid
error.agent.basket.locked=This cart was created by customer service and cannot be modified.
button.clear.cart=Clear All
text.shipping.outside.usa=Shipping outside the USA?
text.select.country=Select Country
label.promocodetotal=Promo Code
label.promocodeapplied=promo code applied to this item
label.campaigns.code=campaigns
