##############################################
# Checkout
##############################################
checkout.emailassociated=This email is associated with an account, please sign in.
description.checkbox.placeorder.condition=I agree to the
button.continue.shipping= Continue to Shipping


##############################################
# Gift Certificate Emails
##############################################
email.giftcertificate.msghasbeenleftforyou=has left the following message for you:
email.giftcertificate.msgleftforyou=The following message has been left for you:
email.giftcertificate.toredeem=To redeem your gift certificate, use the following code within the billing step of the checkout:
email.giftcertificate.dearcustomer=Dear Customer,
email.giftcertificate.dear=Dear {0},
email.giftcertificate.someone=Someone
email.giftcertificate.hassentyou=has sent you a {0} gift certificate for
email.giftcertificate.dwonlinestore=What Goes Around Comes Around
email.giftcertificate.period=.

##############################################
# checkout/shipping /smarty
##############################################
smarty.modal.title=Confirm your address!
smarty.error.notfound=The address entered below is not valid. Please thoroughly review the information to either confirm or change the address.
smarty.error.zipmismatch=The ZIP code entered does not match the selected City and State. Please correct the shipping address to continue.
smarty.suggestion.title=Did you mean?
smarty.user.title=You Entered:
smarty.button.suggestedconfirm=Use corrected address above
smarty.button.changeaddress=Change this Address
smarty.button.confirmaddress=Use my entered address
smarty.suggestion.subtitle=You are almost there! Your order is so important to us and we want to ensure it is going to the correct location. Please review the options below and select the accurate address.
smarty.modal.po.title=po box address
smarty.button.ok=Ok
smarty.nopo.label1= Please note, at this time WGACA is not shipping to any PO Box address.
smarty.nopo.label2=Please enter another address at this time for us to ship your selected product.
label.no.shipping.po.box=Please note: At this time, WGACA is not shipping to any PO Box addresses. We apologize for the inconvenience.
heading.ship.to.address=Shipping Address
heading.shipping.method=Shipping Method
heading.shipping.method.description = Express shipping options are calculated based on your shipping address
giftcertificate.checkout.apply=Apply
giftcertificate.checkout.placeholder=Enter gift code
heading.payment.method=Payment Method
giftcertificate.checkout.balance=Balance


