link.login.forgotpassword=Forgot Password
button.text.loginform=LOGIN & CONTINUE
button.text.Guest=CONTINUE AS GUEST
action.customer.login=Login/Register
link.login.privacypolicy = Privacy Policy
link.login.termsandconditions = Terms and Conditions
description.privacypolicy.terms.login = By continuing, you agree to our
description.privacypolicy.terms.and = and
label.forgotpassword.heading=Forgot your Password?
label.resetpasswordreceived=Request Received
