submit.offer.button=Make an offer
submit.offer.login.button=Login/Register to Make an Offer
submit.offer.modal.title=Make an offer
submit.offer.modal.exit=&times;
label.social.link=Copy a link to Share {0}
label.einstein.recommendationsHome=Your personal picks
