##############################################
# Create Account Form
##############################################
button.createaccount.registration = REGISTER & CONTINUE

description.privacypolicy.registration=What Goes Around Comes Around does not share or sell personal info.

description.privacypolicy.registration.additional = What Goes Around Comes Around does not share or sell personal info. See

description.privacypolicy.terms.registration = By continuing, you agree to our

link.privacypolicy.terms.registration = Terms and Conditions

link.privacypolicy.registrationCapitalized = Privacy Policy

