faq.label=Frequently Asked Questions
label.suggest.suggetionsfor=Suggestions For
label.suggest.popular.categories=Popular Categories
label.suggest.categories=Categories
label.suggest.popular.brands=Popular Brands
label.search.results.found=Results found:
label.search.noresults.fallback=No search results found:
label.search.noresults.tryfilters=Try Filters:
label.search.noresults.query=No search results found for "{0}".
label.search.noresults.reset=Reset filters and try again.
label.search.price.range.error=Price filter value should be in range {0}
button.all.results=View All Results
