##
# Home
##
home.show.title=What Goes Around Comes Around
account.show.description=What Goes Around Comes Around Home Page
account.show.keywords=What Goes Around Comes Around,Home,Landing

##
# Account controller properties
##
account.show.title=What Goes Around Comes Around - Account
account.show.description=What Goes Around Comes Around - Account
account.show.keywords=What Goes Around Comes Around,Account
account.editprofile.title=What Goes Around Comes Around - Edit Profile
account.editprofile.description=What Goes Around Comes Around - Edit Profile
account.editprofile.keywords=What Goes Around Comes Around,Account,EditProfile
account.editpassword.title=What Goes Around Comes Around - EditPassword
account.editpassword.description=What Goes Around Comes Around - EditPassword
account.editpassword.keywords=What Goes Around Comes Around,Account,EditPassword
account.passwordreset.title=What Goes Around Comes Around - Reset Password
account.passwordreset.description=What Goes Around Comes Around - Reset Password
account.passwordreset.keywords=What Goes Around Comes Around,Account,PasswordReset,Reset,Password
account.setnewpassword.title=What Goes Around Comes Around - New Password
account.setnewpassword.description=What Goes Around Comes Around - New Password
account.setnewpassword.keywords=What Goes Around Comes Around,Account,SetNewPassword,New,Password

##
# Address controller properties
##
address.addaddress.title=What Goes Around Comes Around - Add Address
address.addaddress.description=What Goes Around Comes Around - Add Address
address.addaddress.keywords=What Goes Around Comes Around,Address,AddAddress
address.editaddress.title=What Goes Around Comes Around - Edit Address
address.editaddress.description=What Goes Around Comes Around - Edit Address
address.editaddress.keywords=What Goes Around Comes Around,Address,EditAddress

##
# Cart properties
##
cart.show.title=What Goes Around Comes Around - Cart
cart.show.description=Cart of the What Goes Around Comes Around website
cart.show.keywords=What Goes Around Comes Around,Cart

##
# Checkout properties
# Checkout stages:
# - login
# - shipping
# - payment
# - placeOrder
# - submitted
##
checkout.default.title=What Goes Around Comes Around - Checkout
checkout.default.description=Checkout of the What Goes Around Comes Around website
checkout.default.keywords=What Goes Around Comes Around,Checkout
checkout.login.title=What Goes Around Comes Around - Checkout - Login
checkout.login.description=Checkout - Please login before moving forward
checkout.login.keywords=What Goes Around Comes Around,Checkout,Login
checkout.shipping.title=What Goes Around Comes Around - Checkout - Shipping Details
checkout.shipping.description=Checkout - Enter your shipping address details and shipping method
checkout.shipping.keywords=What Goes Around Comes Around,Checkout,Shipping
checkout.payment.title=What Goes Around Comes Around - Checkout - Payment Details
checkout.payment.description=Checkout - Enter your billing address details and payment method
checkout.payment.keywords=What Goes Around Comes Around,Checkout,Payment
checkout.placeOrder.title=What Goes Around Comes Around - Checkout - Review Order
checkout.placeOrder.description=Checkout - Review your order
checkout.placeOrder.keywords=What Goes Around Comes Around,Checkout,Review
checkout.submitted.title=What Goes Around Comes Around - Checkout
checkout.submitted.description=Checkout of the What Goes Around Comes Around website
checkout.submitted.keywords=What Goes Around Comes Around,Checkout

##
# ContactUs controller properties
##
contactus.landing.title=What Goes Around Comes Around - Contact Us
contactus.landing.description=What Goes Around Comes Around - Contact Us
contactus.landing.keywords=What Goes Around Comes Around,ContactUs

##
# Default controller properties
##
default.start.title=What Goes Around Comes Around
default.start.description=What Goes Around Comes Around
default.start.keywords=What Goes Around Comes Around

##
# Error controller properties
##
error.start.title=What Goes Around Comes Around - Error
error.start.description=What Goes Around Comes Around - Error
error.start.keywords=What Goes Around Comes Around,Error
error.errorcode.title=What Goes Around Comes Around - Error Code
error.errorcode.description=What Goes Around Comes Around - Error Code
error.errorcode.keywords=What Goes Around Comes Around,Error,ErrorCode

##
# Login controller properties
##
login.show.title=What Goes Around Comes Around - Login
login.show.description=What Goes Around Comes Around - Login
login.show.keywords=What Goes Around Comes Around,Login
login.oauthlogin.title=What Goes Around Comes Around - Login
login.oauthlogin.description=What Goes Around Comes Around - Login
login.oauthlogin.keywords=What Goes Around Comes Around,Login,OAuthLogin
login.oauthreentry.title=What Goes Around Comes Around - Login
login.oauthreentry.description=What Goes Around Comes Around - Login
login.oauthreentry.keywords=What Goes Around Comes Around,Login,OAuthReentry

##
# Order controller properties
##
order.confirm.title=What Goes Around Comes Around - Order Confirmation
order.confirm.description=Order confirmation of the What Goes Around Comes Around website
order.confirm.keywords=What Goes Around Comes Around,Order,Confirmation,Thanks
order.track.title=What Goes Around Comes Around - Order Track
order.track.description=Order Track of the What Goes Around Comes Around website
order.track.keywords=What Goes Around Comes Around,Order,Track,Thanks
order.history.title=What Goes Around Comes Around - Order History
order.history.description=Order history of the What Goes Around Comes Around website
order.history.keywords=What Goes Around Comes Around,Order,History,Thanks
order.details.title=What Goes Around Comes Around - Order Details
order.details.description=Order details of the What Goes Around Comes Around website
order.details.keywords=What Goes Around Comes Around,Order,Details,Thanks
order.filtered.title=What Goes Around Comes Around - Order Filtered
order.filtered.description=Order filtered of the What Goes Around Comes Around website
order.filtered.keywords=What Goes Around Comes Around,Order,Filtered,Thanks

##
# PaymentInstruments controller properties
##
paymentinstruments.list.title=What Goes Around Comes Around - Payment Methods
paymentinstruments.list.description=What Goes Around Comes Around - Payment Methods
paymentinstruments.list.keywords=What Goes Around Comes Around,PaymentMethods,Payment,Methods
paymentinstruments.addpayment.title=What Goes Around Comes Around - Add Payment Method
paymentinstruments.addpayment.description=What Goes Around Comes Around - Add Payment Method
paymentinstruments.addpayment.keywords=What Goes Around Comes Around,AddPayment,Add,Payment,Method

##
# Stores controller properties
##
stores.find.title=What Goes Around Comes Around - Our Stores
stores.find.description=Our Stores of the What Goes Around Comes Around website
stores.find.keywords=What Goes Around Comes Around,Stores,Find

##
# Wishlist controller properties
##
wishlist.show.title=What Goes Around Comes Around - Wishlist
wishlist.show.description=Wishlist on the What Goes Around Comes Around website
wishlist.show.keywords=What Goes Around Comes Around,Wishlist
wishlist.showothers.title=What Goes Around Comes Around - Wishlist
wishlist.showothers.description=Wishlist on the What Goes Around Comes Around website
wishlist.showothers.keywords=What Goes Around Comes Around,Wishlist
wishlist.search.title=What Goes Around Comes Around - Wishlist Search
wishlist.search.description=Wishlist on the What Goes Around Comes Around website
wishlist.search.keywords=What Goes Around Comes Around,Wishlist


##
# Gift Certificate controller properties
##
giftcertificate.purchase.title=What Goes Around Comes Around - Gift Certificates
giftcertificate.purchase.description=Gift Certificates on the What Goes Around Comes Around website
giftcertificate.purchase.keywords=What Goes Around Comes Around,Gift,Certificate,GiftCertificate