link.move.to.wishlist=Add to wishlist
link.remove.from.wishlist=Remove from wishlist
button.modal.remove=REMOVE
text.modal.restrictspecialcharacters=\^\[\^<\>&\'\"\]\+\$
text.modal.invalidcharactersmessage = Enter a valid name without special symbols